CREATE TABLE TBBIOLOGICALSEX (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMENT ON TABLE TBBIOLOGICALSEX IS 'TABLE TO STORE BIOLOGICAL SEX CATEGORIES.';
COMMENT ON COLUMN TBBIOLOGICALSEX.ID_ IS 'UNIQUE IDENTIFIER FOR THE BIOLOGICAL SEX CATEGORY.';
COMMENT ON COLUMN TBBIOLOGICALSEX.NAME IS 'NAME OF THE BIOLOGICAL SEX CATEGORY.';
COMMENT ON COLUMN TBBIOLOGICALSEX.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE BIOLOGICAL SEX CATEGORY.';

INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('MASCULINO', NULL);
INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('FEMININO', NULL);
INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('INTERSEXO', NULL);

COMMIT WORK;

CREATE TABLE TBGENDEREXPRESSION (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMENT ON TABLE TBGENDEREXPRESSION IS 'TABLE TO STORE GENDER EXPRESSION CATEGORIES.';
COMMENT ON COLUMN TBGENDEREXPRESSION.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.NAME IS 'NAME OF THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER EXPRESSION CATEGORY.';

INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('MASCULINA', NULL);
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FEMININA', NULL);
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('ANDROGINA', NULL);
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FLUIDA', NULL);
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('NAO BINARIA', NULL);

COMMIT WORK;

CREATE TABLE TBGENDERIDENTITY (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMENT ON TABLE TBGENDERIDENTITY IS 'TABLE TO STORE GENDER IDENTITY CATEGORIES.';
COMMENT ON COLUMN TBGENDERIDENTITY.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.NAME IS 'NAME OF THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER IDENTITY CATEGORY.';

INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('CISGENERO', NULL);
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('TRANSGENERO', NULL);
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('INTERSEXUAL', NULL);

COMMIT WORK;

CREATE TABLE TBSEXUALORIENTATION (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMENT ON TABLE TBSEXUALORIENTATION IS 'TABLE TO STORE SEXUAL ORIENTATION CATEGORIES.';
COMMENT ON COLUMN TBSEXUALORIENTATION.ID_ IS 'UNIQUE IDENTIFIER FOR THE SEXUAL ORIENTATION CATEGORY.';
COMMENT ON COLUMN TBSEXUALORIENTATION.NAME IS 'NAME OF THE SEXUAL ORIENTATION CATEGORY.';
COMMENT ON COLUMN TBSEXUALORIENTATION.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE SEXUAL ORIENTATION CATEGORY.';

INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('HETEROSSEXUAL', NULL);
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('HOMOSSEXUAL', NULL);
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('BISSEXUAL', NULL);
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('ASSEXUAL', NULL);
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('PANSEXUAL', NULL);

COMMIT WORK;