DROP TRIGGER BI_EMOTIONAL_ASPECT_ID;
DROP TRIGGER BI_FAMILY_HISTORY_ID;
DROP TRIGGER BI_HEALTH_HISTORY_ID;
DROP TRIGGER BI_MAIN_COMPLAINT_ID;
DROP TRIGGER BI_PATIENT_IDENTIFICATION_ID;
DROP TRIGGER BI_PROFESSIONAL_HISTORY_ID;
DROP TRIGGER BI_ROUTINE_HABIT_ID;
DROP TRIGGER BI_SOCIAL_HISTORY_ID;
DROP TRIGGER BI_THERAPY_EXPECTATION_ID;
DROP TRIGGER BI_ACADEMIC_HISTORY_ID;
DROP TRIGGER BI_CHAPTER_ANAMNESIS_ID;
DROP TRIGGER BI_QUESTION_SCHEDULE_ID;

DROP GENERATOR SQ_ACADEMIC_HISTORY_ID;
DROP GENERATOR SQ_CHAPTER_ANAMNESIS_ID;
DROP GENERATOR SQ_EMOTIONAL_ASPECT_ID;
DROP GENERATOR SQ_FAMILY_HISTORY_ID;
DROP GENERATOR SQ_HEALTH_HISTORY_ID;
DROP GENERATOR SQ_MAIN_COMPLAINT_ID;
DROP GENERATOR SQ_PATIENT_IDENTIFICATION_ID;
DROP GENERATOR SQ_PROFESSIONAL_HISTORY_ID;
DROP GENERATOR SQ_ROUTINE_HABIT_ID;
DROP GENERATOR SQ_SOCIAL_HISTORY_ID;
DROP GENERATOR SQ_THERAPY_EXPECTATION_ID;
DROP GENERATOR SQ_QUESTION_SCHEDULE_ID;

DROP TABLE PATIENT_IDENTIFICATION;
DROP TABLE MAIN_COMPLAINT;
DROP TABLE FAMILY_HISTORY;
DROP TABLE HEALTH_HISTORY;
DROP TABLE PROFESSIONAL_HISTORY;
DROP TABLE SOCIAL_HISTORY;
DROP TABLE ACADEMIC_HISTORY;
DROP TABLE THERAPY_EXPECTATION;
DROP TABLE ROUTINE_HABIT;
DROP TABLE EMOTIONAL_ASPECT;
DROP TABLE QUESTION_SCHEDULE;
DROP TABLE CHAPTER_ANAMNESIS;

DROP TRIGGER BI_FAMILY_CENTER_ID;
DROP GENERATOR SQ_FAMILY_CENTER_ID;
DROP TABLE FAMILY_CENTER;

DROP TRIGGER BI_RESIDENTIAL_ADDRESS_ID;
DROP GENERATOR SQ_RESIDENTIAL_ADDRESS_ID;
DROP TABLE RESIDENTIAL_ADDRESS;

DROP TRIGGER BI_CUSTOMER_REGISTRATION_ID;
DROP GENERATOR SQ_CUSTOMER_REGISTRATION_ID;
DROP TABLE CUSTOMER_REGISTRATION;

DROP TRIGGER BI_METADATA_ID;
DROP GENERATOR SQ_METADATA_ID;
DROP TABLE METADATA;

DROP TRIGGER BI_BIOLOGICAL_SEX_ID;
DROP GENERATOR SQ_BIOLOGICAL_SEX_ID;
DROP TABLE BIOLOGICAL_SEX;

DROP TRIGGER BI_GENDER_EXPRESSION_ID;
DROP GENERATOR SQ_GENDER_EXPRESSION_ID;
DROP TABLE GENDER_EXPRESSION;

DROP TRIGGER BI_GENDER_IDENTITY_ID;
DROP GENERATOR SQ_GENDER_IDENTITY_ID;
DROP TABLE GENDER_IDENTITY;

DROP TRIGGER BI_SEXUAL_ORIENTATION_ID;
DROP GENERATOR SQ_SEXUAL_ORIENTATION_ID;
DROP TABLE SEXUAL_ORIENTATION;

DROP TRIGGER BI_MARITAL_STATUS_ID;
DROP GENERATOR SQ_MARITAL_STATUS_ID;
DROP TABLE MARITAL_STATUS;

DROP TRIGGER BI_RELIGIOUS_AFFILIATION_ID;
DROP GENERATOR SQ_RELIGIOUS_AFFILIATION_ID;
DROP TABLE RELIGIOUS_AFFILIATION;

DROP TRIGGER BI_JOB_OCCUPATION_ID;
DROP GENERATOR SQ_JOB_OCCUPATION_ID;
DROP TABLE JOB_OCCUPATION;

DROP TRIGGER BI_ETHNIC_GROUP_ID;
DROP GENERATOR SQ_ETHNIC_GROUP_ID;
DROP TABLE ETHNIC_GROUP;

DROP TRIGGER BI_CITY_GEOGRAPHIC_ID;
DROP GENERATOR SQ_CITY_GEOGRAPHIC_ID;
DROP TABLE CITY_GEOGRAPHIC;

DROP TRIGGER BI_STATE_GEOGRAPHIC_ID;
DROP GENERATOR SQ_STATE_GEOGRAPHIC_ID;
DROP TABLE STATE_GEOGRAPHIC;

DROP TRIGGER BI_COUNTRY_GEOGRAPHIC_ID;
DROP GENERATOR SQ_COUNTRY_GEOGRAPHIC_ID;
DROP TABLE COUNTRY_GEOGRAPHIC;

DROP TRIGGER BI_REGISTRATION_STATUS_ID;
DROP GENERATOR SQ_REGISTRATION_STATUS_ID;
DROP TABLE REGISTRATION_STATUS;
