/*
EPSYCHOLOGY
THIS DATABASE WORK FOCUSES ON THE DEVELOPMENT AND IMPLEMENTATION OF AN 
ELECTRONIC PSYCHOLOGICAL RECORD, CALLED EPSI, INTENDED FOR THE PSYCHOLOGY 
AND NUTRITION SCHOOL CLINIC IN THE CITY OF ARAÇATUBA, SÃO PAULO. 
THE PROJECT IS ALIGNED WITH THE HEALTH AND WELLBEING SUSTAINABLE 
DEVELOPMENT GOAL (SDG), AIMING TO PROVIDE A SAFE AND EFFICIENT ELECTRONIC 
SYSTEM FOR STORING AND MANAGING PSYCHOLOGICAL RECORDS.
*/

CREATE DATABASE EPSYCHOLOGY;
USE EPSYCHOLOGY;

/*
SOFTWARE UPDATE NOTICE
JULY 4, 2024, DIVERSITY AND INCLUSION, ALPHA 1.1

DEAR ALL,

WE ARE PLEASED TO ANNOUNCE AN IMPORTANT UPDATE TO OUR SOFTWARE. 
THIS UPDATE AIMS TO MAKE OUR SYSTEM MORE INCLUSIVE AND COMPREHENSIVE, 
REFLECTING THE DIVERSITY AND COMPLEXITY OF SEXUAL AND GENDER IDENTITIES 
AND ORIENTATIONS.

NEW IMPLEMENTATIONS:

BIOLOGICAL SEX TABLE (TBBIOLOGICALSEX)
SEXUAL ORIENTATION TABLE (TBSEXUALORIENTATION)
GENDER EXPRESSION TABLE (TBGENDEREXPRESSION)
GENDER IDENTITY TABLE (TBGENDERIDENTITY)

THANK YOU FOR YOUR TRUST, AND WE HOPE THESE UPDATES CONTRIBUTE TO A 
BETTER USER EXPERIENCE. WE ARE AVAILABLE FOR ANY QUESTIONS OR NEEDS.

SINCERELY,
LUCAS DE PAULA MONTI
*/

/*
TABLE TBBIOLOGICALSEX: TABLE TO STORE BIOLOGICAL SEX CATEGORIES
*/

CREATE TABLE TBBIOLOGICALSEX (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBBIOLOGICALSEX IS 'TABLE TO STORE BIOLOGICAL SEX CATEGORIES.';
COMMENT ON COLUMN TBBIOLOGICALSEX.ID_ IS 'UNIQUE IDENTIFIER FOR THE BIOLOGICAL SEX CATEGORY.';
COMMENT ON COLUMN TBBIOLOGICALSEX.NAME IS 'NAME OF THE BIOLOGICAL SEX CATEGORY.';
COMMENT ON COLUMN TBBIOLOGICALSEX.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE BIOLOGICAL SEX CATEGORY.';

COMMIT WORK;

INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('MASCULINO', 
'UMA PESSOA COM CROMOSSOMOS XY GERALMENTE TEM ORGAOS SEXUAIS E REPRODUTIVOS MASCULINOS E PORTANTO GERALMENTE E DESIGNADA COMO DO SEXO MASCULINO.');
INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('FEMININO', 
'UMA PESSOA COM CROMOSSOMOS XX GERALMENTE TEM ORGAOS SEXUAIS E REPRODUTIVOS FEMININOS E PORTANTO GERALMENTE E DESIGNADA COMO DO SEXO FEMININO.');
INSERT INTO TBBIOLOGICALSEX (NAME, OBSERVATION) VALUES ('INTERSEXO', 
'OUTRAS COMBINACOES DE CROMOSSOMOS HORMONIOS E ORGAOS QUE PODEM LEVAR UMA PESSOA A SER CONSIDERADA INTERSEXUAL.');

COMMIT WORK;

/*
TABLE TBSEXUALORIENTATION: TABLE TO STORE SEXUAL ORIENTATION CATEGORIES
*/

CREATE TABLE TBSEXUALORIENTATION (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBSEXUALORIENTATION IS 'TABLE TO STORE SEXUAL ORIENTATION CATEGORIES.';
COMMENT ON COLUMN TBSEXUALORIENTATION.ID_ IS 'UNIQUE IDENTIFIER FOR THE SEXUAL ORIENTATION CATEGORY.';
COMMENT ON COLUMN TBSEXUALORIENTATION.NAME IS 'NAME OF THE SEXUAL ORIENTATION CATEGORY.';
COMMENT ON COLUMN TBSEXUALORIENTATION.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE SEXUAL ORIENTATION CATEGORY.';

COMMIT WORK;

INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('HETEROSSEXUAL', 
'QUE OU AQUELE QUE SENTE ATRACAO SEXUAL POR E/OU MANTEM RELACAO AMOROSA E/OU SEXUAL COM PESSOA DO SEXO OPOSTO.');
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('HOMOSSEXUAL', 
'QUE OU AQUELE QUE SENTE ATRACAO SEXUAL POR E/OU MANTEM RELACAO AMOROSA E/OU SEXUAL COM PESSOA DO MESMO SEXO.');
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('BISSEXUAL', 
'QUE OU AQUELE QUE SENTE ATRACAO SEXUAL POR E/OU MANTEM RELACAO AMOROSA E/OU SEXUAL COM PESSOA DE AMBOS OS SEXOS.');
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('ASSEXUAL', 
'E A FALTA TOTAL, PARCIAL OU CONDICIONAL DE ATRACAO SEXUAL A QUALQUER PESSOA, INDEPENDENTE DO SEXO BIOLOGICO OU GENERO.');
INSERT INTO TBSEXUALORIENTATION (NAME, OBSERVATION) VALUES ('PANSEXUAL', 
'E A ATRACAO SEXUAL, ROMANTICA OU EMOCIONAL EM RELACAO AS PESSOAS, INDEPENDENTEMENTE DE SEU SEXO OU IDENTIDADE DE GENERO.');

COMMIT WORK;

/*
TABLE TBGENDERIDENTITY: TABLE TO STORE GENDER IDENTITY CATEGORIES
*/

CREATE TABLE TBGENDERIDENTITY (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBGENDERIDENTITY IS 'TABLE TO STORE GENDER IDENTITY CATEGORIES.';
COMMENT ON COLUMN TBGENDERIDENTITY.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.NAME IS 'NAME OF THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER IDENTITY CATEGORY.';

COMMIT WORK;

INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('CISGENERO', 
'E A CONDICAO DA PESSOA CUJA IDENTIDADE DE GENERO CORRESPONDE AO SEXO QUE LHE FOI ATRIBUIDO NO NASCIMENTO.');
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('TRANSGENERO', 
'SAO PESSOAS CUJA IDENTIDADE DE GENERO DIFERE DO TIPICO DO SEU SEXO, ATRIBUIDO AO NASCER.');
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('INTERSEXUAL', 
'E A PESSOA QUE NATURALMENTE DESENVOLVE CARACTERISTICAS SEXUAIS QUE NAO SE ENCAIXAM NAS NOCOES TIPICAS DE SEXO FEMININO OU SEXO MASCULINO.');

COMMIT WORK;

/*
TABLE TBGENDEREXPRESSION: TABLE TO STORE GENDER EXPRESSION CATEGORIES
*/

CREATE TABLE TBGENDEREXPRESSION (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBGENDEREXPRESSION IS 'TABLE TO STORE GENDER EXPRESSION CATEGORIES.';
COMMENT ON COLUMN TBGENDEREXPRESSION.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.NAME IS 'NAME OF THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER EXPRESSION CATEGORY.';

COMMIT WORK;

INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('MASCULINA', 
'A EXPRESSAO DE GENERO QUE POSSUI TRACOS TIPICOS DOS HOMENS E MENINOS E CLASSIFICADA COMO EXPRESSAO DE GENERO MASCULINA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FEMININA', 
'A EXPRESSAO DE GENERO QUE CONTEM CARACTERISTICAS TIPICAS DAS MULHERES E MENINAS E CLASSIFICADA COMO EXPRESSAO DE GENERO FEMININA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('ANDROGINA', 
'UMA EXPRESSAO DE GENERO QUE INCLUA TRACOS TIPICOS DOS HOMENS E MENINOS, E TRACOS TIPICOS DAS MULHERES E MENINAS, E CLASSIFICADA COMO ANDROGINA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FLUIDA', 
'E A NAO IDENTIFICACAO COM UM UNICO PAPEL DE GENERO OU IDENTIDADE DE GENERO, FLUINDO ENTRE VARIOS. SAO TAMBEM AQUELAS CUJO GENERO E INSOLITO OU MUDA DE TEMPOS EM TEMPOS.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('NAO BINARIA', 
'E UM TERMO GUARDA-CHUVA PARA IDENTIDADES DE GENERO QUE NAO SAO ESTRITAMENTE MASCULINAS OU FEMININAS, ESTANDO PORTANTO FORA DO BINARIO DE GENERO E DA CISNORMATIVIDADE.');

COMMIT WORK;

/*
SOFTWARE UPDATE NOTICE
JULY 4, 2024, MAPPING, ALPHA 1.2

DEAR ALL,

WE ARE PLEASED TO ANNOUNCE A NEW UPDATE TO OUR SOFTWARE, WHICH INCLUDES THE IMPLEMENTATION OF A 
NEW TABLE DEDICATED TO MANAGING INFORMATION ABOUT COUNTRIES, STATES, AND CITIES. THIS UPDATE AIMS 
TO ENHANCE THE ORGANIZATION AND EFFICIENCY IN THE ADMINISTRATION OF GEOGRAPHICAL DATA.

NEW IMPLEMENTATIONS:

COUNTRIES TABLE (TBCOUNTRY)
STATES TABLE (TBSTATE)
CITIES TABLE (TBCITY)

THANK YOU FOR YOUR TRUST, AND WE ARE AVAILABLE FOR ANY QUESTIONS OR NECESSARY SUPPORT.

SINCERELY,
LUCAS DE PAULA MONTI
*/

/*
TABLE TBCOUNTRY: TABLE CONTAINING INFORMATION ABOUT COUNTRIES
*/

CREATE TABLE TBCOUNTRY(
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE
);

COMMIT WORK;

COMMENT ON TABLE TBCOUNTRY IS 'TABLE CONTAINING INFORMATION ABOUT COUNTRIES';
COMMENT ON COLUMN TBCOUNTRY.ID_ IS 'UNIQUE IDENTIFIER FOR EACH COUNTRY';
COMMENT ON COLUMN TBCOUNTRY.NAME IS 'NAME OF THE COUNTRY';

COMMIT WORK;

INSERT INTO TBCOUNTRY (NAME) VALUES ('BRASIL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AFEGANISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AFRICA DO SUL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AKROTIRI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ALBANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ALEMANHA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ANDORRA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ANGOLA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ANGUILA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ANTARCTIDA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ANTIGUA E BARBUDA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARABIA SAUDITA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARCTIC OCEAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARGELIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARGENTINA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARMENIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ARUBA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ASHMORE AND CARTIER ISLANDS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ATLANTIC OCEAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AUSTRALIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AUSTRIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('AZERBAIJAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BAAMAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BANGLADECHE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BARBADOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BAREM');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BELGICA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BELIZE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BENIM');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BERMUDAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BIELORRUSSIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BIRMANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BOLIVIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BOSNIA E HERZEGOVINA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BOTSUANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BRUNEI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BULGARIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BURQUINA FASO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BURUNDI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('BUTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CABO VERDE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CAMAROES');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CAMBOJA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CANADA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CATAR');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CAZAQUISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CHADE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CHILE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CHINA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CHIPRE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CLIPPERTON ISLAND');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COLOMBIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COMORES');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CONGO-BRAZZAVILLE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CONGO-KINSHASA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CORAL SEA ISLANDS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COREIA DO NORTE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COREIA DO SUL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COSTA DO MARFIM');
INSERT INTO TBCOUNTRY (NAME) VALUES ('COSTA RICA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CROACIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CUBA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('CURACAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('DHEKELIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('DINAMARCA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('DOMINICA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('EGIPTO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('EMIRATOS ARABES UNIDOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('EQUADOR');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ERITREIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ESLOVAQUIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ESLOVENIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ESPANHA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ESTADOS UNIDOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ESTONIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ETIOPIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('FAROE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('FIJI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('FILIPINAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('FINLANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('FRANÇA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GABAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GAMBIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GAZA STRIP');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GEORGIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GEORGIA DO SUL E SANDWICH DO SUL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GIBRALTAR');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GRANADA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GRECIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GRONELANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUAME');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUATEMALA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUERNSEY');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUIANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUINE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUINE EQUATORIAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('GUINE-BISSAU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('HAITI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('HONDURAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('HONG KONG');
INSERT INTO TBCOUNTRY (NAME) VALUES ('HUNGRIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('IEMEN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHA BOUVET');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHA DO NATAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHA NORFOLK');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS CAIMAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS COOK');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS DOS COCOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS FALKLAND');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS HEARD E MCDONALD');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS MARSHALL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS SALOMAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS TURCAS E CAICOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS VIRGENS AMERICANAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ILHAS VIRGENS BRITANICAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('INDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('INDIAN OCEAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('INDONESIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('IRAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('IRAQUE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('IRLANDA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ISLANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ISRAEL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ITALIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JAMAICA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JAN MAYEN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JAPAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JERSEY');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JIBUTI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('JORDANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('KOSOVO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('KUWAIT');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LAOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LESOTO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LETONIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LIBANO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LIBERIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LIBIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LISTENSTAINE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LITUANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('LUXEMBURGO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MACAU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MACEDONIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MADAGASCAR');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MALASIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MALAVI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MALDIVAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MALI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MALTA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MAN, ISLE OF');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MARIANAS DO NORTE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MARROCOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MAURICIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MAURITANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MEXICO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MICRONESIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MOÇAMBIQUE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MOLDAVIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MONACO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MONGOLIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MONSERRATE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MONTENEGRO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('MUNDO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NAMIBIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NAURU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NAVASSA ISLAND');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NEPAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NICARAGUA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NIGER');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NIGERIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NIUE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NORUEGA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NOVA CALEDONIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('NOVA ZELANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('OMA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PACIFIC OCEAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PAISES BAIXOS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PALAU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PANAMA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PAPUA-NOVA GUINE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PAQUISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PARACEL ISLANDS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PARAGUAI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PERU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PITCAIRN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('POLINESIA FRANCESA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('POLONIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PORTO RICO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('PORTUGAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('QUENIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('QUIRGUIZISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('QUIRIBATI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('REINO UNIDO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('REPUBLICA CENTRO-AFRICANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('REPUBLICA DOMINICANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ROMENIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('RUANDA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('RUSSIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SALVADOR');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAMOA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAMOA AMERICANA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SANTA HELENA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SANTA LUCIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO BARTOLOMEU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO CRISTOVAO E NEVES');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO MARINHO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO MARTINHO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO PEDRO E MIQUELON');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO TOME E PRINCIPE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SAO VICENTE E GRANADINAS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SARA OCIDENTAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SEICHELES');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SENEGAL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SERRA LEOA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SERVIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SINGAPURA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SINT MAARTEN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SIRIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SOMALIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SOUTHERN OCEAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SPRATLY ISLANDS');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SRI LANCA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SUAZILANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SUDAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SUDAO DO SUL');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SUECIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SUIÇA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SURINAME');
INSERT INTO TBCOUNTRY (NAME) VALUES ('SVALBARD E JAN MAYEN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TAILANDIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TAIWAN');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TAJIQUISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TANZANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TERRITORIO BRITANICO DO OCEANO INDICO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TERRITORIOS AUSTRAIS FRANCESES');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TIMOR LESTE');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TOGO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TOKELAU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TONGA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TRINDADE E TOBAGO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TUNISIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TURQUEMENISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TURQUIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('TUVALU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('UCRANIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('UGANDA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('UNIAO EUROPEIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('URUGUAI');
INSERT INTO TBCOUNTRY (NAME) VALUES ('USBEQUISTAO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('VANUATU');
INSERT INTO TBCOUNTRY (NAME) VALUES ('VATICANO');
INSERT INTO TBCOUNTRY (NAME) VALUES ('VENEZUELA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('VIETNAME');
INSERT INTO TBCOUNTRY (NAME) VALUES ('WAKE ISLAND');
INSERT INTO TBCOUNTRY (NAME) VALUES ('WALLIS E FUTUNA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('WEST BANK');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ZAMBIA');
INSERT INTO TBCOUNTRY (NAME) VALUES ('ZIMBABUE');

COMMIT WORK;

/*
TABLE TBSTATE: TABLE CONTAINING INFORMATION ABOUT STATES
*/

CREATE TABLE TBSTATE(
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    IDCOUNTRY_ INTEGER NOT NULL,

    FOREIGN KEY (IDCOUNTRY_) REFERENCES TBCOUNTRY(ID_)
);

COMMIT WORK;

COMMENT ON TABLE TBSTATE IS 'TABLE CONTAINING INFORMATION ABOUT STATES';
COMMENT ON COLUMN TBSTATE.ID_ IS 'UNIQUE IDENTIFIER FOR EACH STATE';
COMMENT ON COLUMN TBSTATE.NAME IS 'NAME OF THE STATE';
COMMENT ON COLUMN TBSTATE.IDCOUNTRY_ IS 'FOREIGN KEY REFERENCING THE UNIQUE IDENTIFIER OF THE COUNTRY IN THE TBCOUNTRY TABLE';

COMMIT WORK;

INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ACRE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ALAGOAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('AMAPA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('AMAZONAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('BAHIA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('CEARA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ESPIRITO SANTO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('GOIAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MARANHAO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MATO GROSSO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MATO GROSSO DO SUL', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MINAS GERAIS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARAIBA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARANA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PERNAMBUCO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PIAUI', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO DE JANEIRO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO GRANDE DO NORTE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO GRANDE DO SUL', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RONDONIA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RORAIMA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SANTA CATARINA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SAO PAULO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SERGIPE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('TOCANTINS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('DISTRITO FEDERAL', 1);

COMMIT WORK;

/*
TABLE TBCITY: TABLE CONTAINING INFORMATION ABOUT CITIES
*/

CREATE TABLE TBCITY (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    IDSTATE_ INTEGER NOT NULL,

    FOREIGN KEY (IDSTATE_) REFERENCES TBSTATE(ID_)
);

COMMIT WORK;

COMMENT ON TABLE TBCITY IS 'TABLE CONTAINING INFORMATION ABOUT CITIES';
COMMENT ON COLUMN TBCITY.ID_ IS 'UNIQUE IDENTIFIER FOR EACH CITY';
COMMENT ON COLUMN TBCITY.NAME IS 'NAME OF THE CITY';
COMMENT ON COLUMN TBCITY.IDSTATE_ IS 'FOREIGN KEY REFERENCING THE UNIQUE IDENTIFIER OF THE STATE IN THE TBSTATE TABLE';

COMMIT WORK;

INSERT INTO TBCITY (NAME, IDSTATE_) VALUES ('ARACATUBA', 24);
INSERT INTO TBCITY (NAME, IDSTATE_) VALUES ('BIRIGUI', 24);
INSERT INTO TBCITY (NAME, IDSTATE_) VALUES ('GUARARAPES', 24);

COMMIT WORK;

/*
SOFTWARE UPDATE NOTICE
AUGUST 14, 2024, PERSONNALITE, ALPHA 1.3

DEAR ALL,

WE ARE PLEASED TO ANNOUNCE A NEW UPDATE TO OUR SOFTWARE, WHICH INCLUDES THE IMPLEMENTATION 
OF A NEW TABLE DEDICATED TO MANAGING INFORMATION ABOUT BLOOD TYPES, MARITAL STATUS, RELIGIONS AND ZOODIAC. 
THE OBJECTIVE OF THIS IMPLEMENTATION IS TO MAKE CUSTOMER REGISTRATION MORE CUSTOMIZABLE AND REALISTIC.

NEW IMPLEMENTATIONS:

BLOOD TYPES TABLE (TBBLOOD)
MARITAL STATUS TABLE (TBMARITAL)
RELIGIONS TABLE (TBRELIGION)
ZOODIAC TABLE (TBZOODIAC)

THANK YOU FOR YOUR TRUST, AND WE ARE AVAILABLE FOR ANY QUESTIONS OR NECESSARY SUPPORT.

SINCERELY,
LUCAS DE PAULA MONTI
*/

/*
TABLE TBBLOOD: TABLE THAT STORES INFORMATION ABOUT BLOOD TYPES
*/

CREATE TABLE TBBLOOD (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	HEMACY CHAR(2) NOT NULL,
	AGLUTININ VARCHAR(8),
	RHFACTOR CHAR(1) NOT NULL,
	ACRONYM VARCHAR(15) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBBLOOD IS 'TABLE THAT STORES INFORMATION ABOUT BLOOD TYPES.';
COMMENT ON COLUMN TBBLOOD.HEMACY IS 'TYPE OF RBC, REPRESENTED BY THE LETTERS A, B, AB OR O.';
COMMENT ON COLUMN TBBLOOD.AGLUTININ IS 'AGLUTININ PRESENT IN PLASMA, AS ANTI-A, ANTI-B, OR NULL IN THE CASE OF AB.';
COMMENT ON COLUMN TBBLOOD.RHFACTOR IS 'BLOOD RH FACTOR, REPRESENTED BY "+" FOR POSITIVE AND "-" FOR NEGATIVE.';
COMMENT ON COLUMN TBBLOOD.ACRONYM IS 'ACRONYM THAT COMBINES BLOOD TYPE WITH AGLUTININ AND RH FACTOR.';
COMMENT ON COLUMN TBBLOOD.OBSERVATION IS 'OBSERVATION FIELD FOR ADDITIONAL INFORMATION ABOUT BLOOD TYPE.';

COMMIT WORK;

INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('A', 'ANTI-B', '+', 'A+ ANTI-B', 'TIPO SANGUÍNEO A POSITIVO COM AGLUTININA ANTI-B.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('A', 'ANTI-B', '-', 'A- ANTI-B', 'TIPO SANGUÍNEO A NEGATIVO COM AGLUTININA ANTI-B.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('B', 'ANTI-A', '+', 'B+ ANTI-A', 'TIPO SANGUÍNEO B POSITIVO COM AGLUTININA ANTI-A.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('B', 'ANTI-A', '-', 'B- ANTI-A', 'TIPO SANGUÍNEO B NEGATIVO COM AGLUTININA ANTI-A.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('AB', NULL, '+', 'AB+', 'TIPO SANGUÍNEO AB POSITIVO SEM AGLUTININAS.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('AB', NULL, '-', 'AB-', 'TIPO SANGUÍNEO AB NEGATIVO SEM AGLUTININAS.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('O', 'ANTI-AB', '+', 'O+ ANTI-AB', 'TIPO SANGUÍNEO O POSITIVO COM AGLUTININAS ANTI-A E ANTI-B.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('O', 'ANTI-AB', '-', 'O- ANTI-AB', 'TIPO SANGUÍNEO O NEGATIVO COM AGLUTININAS ANTI-A E ANTI-B.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('O', 'ANTI-ABH', '+', 'F(O+) ANTI-ABH', 'FENOTIPO BOMBAY (FALSO O) POSITIVO COM AGLUTININAS ANTI-A, ANTI-B E ANTI-H.');
INSERT INTO TBBLOOD (HEMACY, AGLUTININ, RHFACTOR, ACRONYM, OBSERVATION) 
VALUES ('O', 'ANTI-ABH', '-', 'F(O-) ANTI-ABH', 'FENOTIPO BOMBAY (FALSO O) NEGATIVO COM AGLUTININAS ANTI-A, ANTI-B E ANTI-H.');

COMMIT WORK;

/*
TABLE TBMARITAL: MARITAL STATUS TABLE
*/

CREATE TABLE TBMARITAL(
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBMARITAL IS 'MARITAL STATUS TABLE';
COMMENT ON COLUMN TBMARITAL.ID_ IS 'UNIQUE MARITAL STATUS IDENTIFIER';
COMMENT ON COLUMN TBMARITAL.NAME IS 'MARITAL STATUS NAME';
COMMENT ON COLUMN TBMARITAL.OBSERVATION IS 'FIELD FOR ADDITIONAL OBSERVATIONS ON MARITAL STATUS';

COMMIT WORK;

INSERT INTO TBMARITAL (NAME, OBSERVATION) VALUES ('SOLTEIRO', 'PESSOA QUE NUNCA SE CASOU.');
INSERT INTO TBMARITAL (NAME, OBSERVATION) VALUES ('CASADO', 'PESSOA ATUALMENTE CASADA.');
INSERT INTO TBMARITAL (NAME, OBSERVATION) VALUES ('SEPARADO', 'PESSOA SEPARADA LEGALMENTE, MAS NAO DIVORCIADA.');
INSERT INTO TBMARITAL (NAME, OBSERVATION) VALUES ('DIVORCIADO', 'PESSOA QUE FOI CASADA E OBTEVE DIVORCIO.');
INSERT INTO TBMARITAL (NAME, OBSERVATION) VALUES ('VIUVO', 'PESSOA CUJO CONJUGE FALECEU.');

COMMIT WORK;

/*
TABLE TBRELIGION: TABLE FOR STORING INFORMATION ABOUT RELIGIONS
*/

CREATE TABLE TBRELIGION (
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBRELIGION IS 'TABLE FOR STORING INFORMATION ABOUT RELIGIONS';
COMMENT ON COLUMN TBRELIGION.ID_ IS 'UNIQUE RELIGION ID';
COMMENT ON COLUMN TBRELIGION.NAME IS 'NAME OF RELIGION';
COMMENT ON COLUMN TBRELIGION.OBSERVATION IS 'FIELD FOR ADDITIONAL OBSERVATIONS ON RELIGION';

COMMIT WORK;

INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('CRISTIANISMO', 'RELIGIAO BASEADA NOS ENSINAMENTOS DE JESUS CRISTO.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('CATOLICISMO', 'RAMO DO CRISTIANISMO LIDERADO PELA IGREJA CATOLICA.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('PROTESTANTISMO', 'RAMO DO CRISTIANISMO ORIGINADO DA REFORMA PROTESTANTE.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('ADVENTISMO', 'MOVIMENTO RELIGIOSO CRISTAO QUE ENFATIZA A IMINENTE SEGUNDA VINDA DE CRISTO.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('ANGLICANISMO', 'RAMO DO CRISTIANISMO QUE TEM SUAS RAIZES NA IGREJA DA INGLATERRA.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('TESTEMUNHA DE JEOVA', 'MOVIMENTO CRISTAO CONHECIDO POR SUA INTERPRETACAO UNICA DA BIBLIA.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('MORMONISMO', 'RELIGIAO CRISTA RESTAURACIONISTA ORIGINADA NO SECULO XIX.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('IGREJA ORTODOXA', 'RAMO DO CRISTIANISMO PREDOMINANTEMENTE PRATICADO NO LESTE EUROPEU.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('ESPIRITISMO', 'DOUTRINA ESPIRITUALISTA QUE ACREDITA NA COMUNICACAO COM OS ESPIRITOS.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('ISLAMISMO', 'RELIGIAO MONOTEISTA BASEADA NOS ENSINAMENTOS DO PROFETA MAOME.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('JUDAISMO', 'RELIGIAO MONOTEISTA E CULTURAL DO POVO JUDEU.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('NEOPAGANISMO', 'MOVIMENTO RELIGIOSO QUE REVIVER PRATICAS PAGAS ANTIGAS.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('HINDUISMO', 'RELIGIAO PREDOMINANTE NA INDIA, CARACTERIZADA PELA CRENCA EM VARIOS DEUSES.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('SANTO DAIME', 'SINCRETISMO RELIGIOSO QUE MISTURA ELEMENTOS CRISTAOS E INDIGENAS.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('CANDOMBLE', 'RELIGIAO AFRO-BRASILEIRA QUE ENVOLVE O CULTO AOS ORIXAS.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('UMBANDA', 'RELIGIAO BRASILEIRA QUE MISTURA ELEMENTOS AFRICANOS, INDIGENAS E CRISTAOS.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('AGNOSTICO', 'PESSOA QUE ACREDITA QUE A EXISTENCIA DE DEUS E DESCONHECIDA OU INCOGNOSCIVEL.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('ATEU', 'PESSOA QUE NAO ACREDITA NA EXISTENCIA DE DEUS OU DEUSES.');
INSERT INTO TBRELIGION (NAME, OBSERVATION) VALUES ('SEM RELIGIAO', 'PESSOA QUE NAO SEGUE OU SE IDENTIFICA COM UMA RELIGIAO ESPECIFICA.');

COMMIT WORK;

/*
TABLE ZOODIAC: TABLE FOR STORING ZODIAC SIGNS
*/

CREATE TABLE TBZOODIAC (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(15) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBZOODIAC IS 'TABLE FOR STORING ZODIAC SIGNS';
COMMENT ON COLUMN TBZOODIAC.ID_ IS 'UNIQUE IDENTIFIER FOR EACH ZODIAC SIGN';
COMMENT ON COLUMN TBZOODIAC.NAME IS 'ZODIAC SIGN NAME';
COMMENT ON COLUMN TBZOODIAC.OBSERVATION IS 'FIELD FOR ADDITIONAL OBSERVATIONS ABOUT THE ZODIAC SIGN';

COMMIT WORK;

INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('ARIES', 'SIGNO DE FOGO, REGIDO POR MARTE.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('TOURO', 'SIGNO DE TERRA, REGIDO POR VENUS.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('GEMEOS', 'SIGNO DE AR, REGIDO POR MERCURIO.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('CANCER', 'SIGNO DE AGUA, REGIDO PELA LUA.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('LEAO', 'SIGNO DE FOGO, REGIDO PELO SOL.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('VIRGEM', 'SIGNO DE TERRA, REGIDO POR MERCURIO.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('LIBRA', 'SIGNO DE AR, REGIDO POR VENUS.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('ESCORPIAO', 'SIGNO DE AGUA, REGIDO POR PLUTAO E MARTE.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('SAGITARIO', 'SIGNO DE FOGO, REGIDO POR JUPITER.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('CAPRICORNIO', 'SIGNO DE TERRA, REGIDO POR SATURNO.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('AQUARIO', 'SIGNO DE AR, REGIDO POR URANO E SATURNO.');
INSERT INTO TBZOODIAC (NAME, OBSERVATION) VALUES ('PEIXES', 'SIGNO DE AGUA, REGIDO POR NETUNO E JUPITER.');

COMMIT WORK;

/*

*/

CREATE TABLE TBETHNICITY (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(15) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBETHNICITY IS '';
COMMENT ON COLUMN TBETHNICITY.ID_ IS '';
COMMENT ON COLUMN TBETHNICITY.NAME IS '';
COMMENT ON COLUMN TBETHNICITY.OBSERVATION IS '';

COMMIT WORK;

INSERT INTO TBETHNICITY (NAME, OBSERVATION) VALUES ('BRANCO', '');
INSERT INTO TBETHNICITY (NAME, OBSERVATION) VALUES ('PARDO', '');
INSERT INTO TBETHNICITY (NAME, OBSERVATION) VALUES ('NEGRO', '');
INSERT INTO TBETHNICITY (NAME, OBSERVATION) VALUES ('INDIGENA', '');
INSERT INTO TBETHNICITY (NAME, OBSERVATION) VALUES ('AMARELO', '');

COMMIT WORK;

/*

*/

CREATE TABLE TBOCCUPATION (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBOCCUPATION IS '';
COMMENT ON COLUMN TBOCCUPATION.ID_ IS '';
COMMENT ON COLUMN TBOCCUPATION.NAME IS '';
COMMENT ON COLUMN TBOCCUPATION.OBSERVATION IS '';

COMMIT WORK;

INSERT INTO TBOCCUPATION (NAME, OBSERVATION) VALUES ('DESEMPREGADO', '');

/*

*/

CREATE TABLE TBCUSTOMER (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	NAMEBIOLOGICAL VARCHAR(150) NOT NULL,
	NAMESOCIAL VARCHAR(150),
	BIRTHDATE DATE,
	
	DOCCPF VARCHAR(14),
	DOCRG VARCHAR(12),

	IDBIOLOGICALSEX_ INTEGER,
	IDSEXUALORIENTATION_ INTEGER,
	IDGENDEREXPRESSION_ INTEGER,
	IDGENDERIDENTITY_ INTEGER,

	IDMARITAL_ INTEGER,
	IDRELIGION_ INTEGER,
	IDBLOOD_ INTEGER,
	IDZOODIAC_ INTEGER,
	IDETHNICITY_ INTEGER,
	IDOCCUPATION_ INTEGER,

	FOREIGN KEY (IDBIOLOGICALSEX_) REFERENCES TBBIOLOGICALSEX (ID_),
	FOREIGN KEY (IDSEXUALORIENTATION_) REFERENCES TBSEXUALORIENTATION (ID_),
	FOREIGN KEY (IDGENDEREXPRESSION_) REFERENCES TBGENDEREXPRESSION (ID_),
	FOREIGN KEY (IDGENDERIDENTITY_) REFERENCES TBGENDERIDENTITY (ID_),

	FOREIGN KEY (IDMARITAL_) REFERENCES TBMARITAL (ID_),
	FOREIGN KEY (IDRELIGION_) REFERENCES TBRELIGION (ID_),
	FOREIGN KEY (IDBLOOD_) REFERENCES TBBLOOD (ID_),
	FOREIGN KEY (IDZOODIAC_) REFERENCES TBZOODIAC (ID_),
	FOREIGN KEY (IDETHNICITY_) REFERENCES TBETHNICITY (ID_),
	FOREIGN KEY (IDOCCUPATION_) REFERENCES TBOCCUPATION (ID_)
);

/*

*/

CREATE TABLE TBFAMILY (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	IDCUSTOMER_ INTEGER NOT NULL UNIQUE,

	NAMEFATHER VARCHAR(150),
	IDOCCUPATIONFATHER_ INTEGER,
	DDDFATHER CHAR(2),
	FONEFATHER CHAR(11),
	
	NAMEMOTHER VARCHAR(150),
	IDOCCUPATIONMOTHER_ INTEGER,
	DDDMOTHER CHAR(2),
	FONEMOTHER CHAR(11),
	
	NAMEPARTNER VARCHAR(150),
	IDOCCUPATIONPARTNER_ INTEGER,
	DDDPARTNER CHAR(2),
	FONEPARTNER CHAR(11),

	OBSERVATION VARCHAR(255),

	FOREIGN KEY (IDCUSTOMER_) REFERENCES TBCUSTOMER (ID_),
	FOREIGN KEY (IDOCCUPATIONFATHER_) REFERENCES TBOCCUPATION (ID_),
	FOREIGN KEY (IDOCCUPATIONMOTHER_) REFERENCES TBOCCUPATION (ID_),
	FOREIGN KEY (IDOCCUPATIONPARTNER_) REFERENCES TBOCCUPATION (ID_)
);

/*

*/

CREATE TABLE TBADDRESS (
	ID_ SERIAL NOT NULL PRIMARY KEY,
	IDCUSTOMER_ INTEGER NOT NULL UNIQUE,

	ADDRESS VARCHAR(100),
	NUMBER VARCHAR(10),
	DISTRICT VARCHAR(45),
	COMPLEMENT VARCHAR(75),
	CEP CHAR(9),
	IDCITY_ INTEGER,
	
	DDD CHAR(2),
	FONE CHAR(11),
	MAIL VARCHAR(75),
	OBSERVATION VARCHAR(255),

	FOREIGN KEY (IDCUSTOMER_) REFERENCES TBCUSTOMER (ID_),
	FOREIGN KEY (IDCITY_) REFERENCES TBCITY (ID_)
);





