CREATE VIEW VW_SHOW_TABLE AS
SELECT
    RDB$RELATION_NAME,
    RDB$DESCRIPTION
FROM
    RDB$RELATIONS
WHERE
    RDB$RELATIONS.RDB$SYSTEM_FLAG = 0
    AND RDB$RELATIONS.RDB$RELATION_TYPE = 0
ORDER BY
    RDB$RELATION_NAME
;

COMMENT ON VIEW VW_SHOW_TABLE IS 'VIEW THAT LISTS ALL USER CREATED TABLES.';

COMMIT WORK;

CREATE VIEW VW_SHOW_VIEW AS
SELECT
    RDB$RELATION_NAME,
    RDB$DESCRIPTION
FROM
    RDB$RELATIONS
WHERE
    RDB$RELATIONS.RDB$SYSTEM_FLAG = 0
    AND RDB$RELATIONS.RDB$RELATION_TYPE = 1
ORDER BY
    RDB$RELATION_NAME
;

COMMENT ON VIEW VW_SHOW_VIEW IS 'VIEW THAT LISTS ALL USER CREATED VIEWS.';

COMMIT WORK;

CREATE VIEW VW_SHOW_TRIGGER AS
SELECT
    RDB$TRIGGER_NAME,
    RDB$RELATION_NAME,
    CASE RDB$TRIGGER_TYPE
        WHEN 1 THEN 'BEFORE INSERT'
        WHEN 2 THEN 'AFTER INSERT'
        WHEN 3 THEN 'BEFORE UPDATE'
        WHEN 4 THEN 'AFTER UPDATE'
        WHEN 5 THEN 'BEFORE DELETE'
        WHEN 6 THEN 'AFTER DELETE'
        ELSE 'OTHER'
    END RDB$TRIGGER_TYPE,
    RDB$TRIGGER_SEQUENCE,
    RDB$DESCRIPTION,
    CASE RDB$TRIGGER_INACTIVE
        WHEN 0 THEN 'ACTIVE'
        ELSE 'INACTIVE'
    END RDB$TRIGGER_INACTIVE
FROM
    RDB$TRIGGERS
WHERE
    RDB$SYSTEM_FLAG = 0
ORDER BY
    RDB$RELATION_NAME,
    RDB$TRIGGER_SEQUENCE
;

COMMENT ON VIEW VW_SHOW_TRIGGER IS 'VIEW THAT LISTS ALL USER CREATED TRIGGERS.';

COMMIT WORK;

CREATE VIEW VW_SHOW_SEQUENCE AS
SELECT
    RDB$GENERATOR_NAME,
    RDB$DESCRIPTION
FROM
    RDB$GENERATORS
WHERE
    RDB$SYSTEM_FLAG = 0
ORDER BY
    RDB$GENERATOR_NAME
;

COMMENT ON VIEW VW_SHOW_SEQUENCE IS 'VIEW THAT LISTS ALL USER CREATED SEQUENCES.';

COMMIT WORK;

CREATE VIEW VW_SHOW_PROCEDURE AS
SELECT
    RDB$PROCEDURE_NAME,
    RDB$DESCRIPTION
FROM
    RDB$PROCEDURES
ORDER BY
    RDB$PROCEDURE_NAME
;

COMMENT ON VIEW VW_SHOW_PROCEDURE IS 'VIEW THAT LISTS ALL USER CREATED PROCEDURES.';

COMMIT WORK;

/*BIOLOGICAL_SEX*/
CREATE TABLE BIOLOGICAL_SEX (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE BIOLOGICAL_SEX ADD CONSTRAINT PK_BIOLOGICAL_SEX PRIMARY KEY (ID);
ALTER TABLE BIOLOGICAL_SEX ADD CONSTRAINT UQ_BIO_SEX_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE BIOLOGICAL_SEX IS 'TABLE TO STORE BIOLOGICAL SEX VALUES.';
COMMENT ON COLUMN BIOLOGICAL_SEX.ID IS 'UNIQUE IDENTIFIER FOR THE BIOLOGICAL SEX.';
COMMENT ON COLUMN BIOLOGICAL_SEX.DESCRIPTION IS 'DESCRIPTION OF THE BIOLOGICAL SEX.';

CREATE GENERATOR SQ_BIOLOGICAL_SEX;

COMMENT ON GENERATOR SQ_BIOLOGICAL_SEX IS 'GENERATOR FOR TABLE BIOLOGICAL_SEX COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_BIOLOGICAL_SEX
FOR BIOLOGICAL_SEX
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_BIOLOGICAL_SEX;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_BIOLOGICAL_SEX IS 'TRIGGER FOR TABLE BIOLOGICAL_SEX COLUMN ID.';

INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('MASCULINO');
INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('FEMININO');
INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('INTERSEXO');

COMMIT WORK;

/*GENDER_EXPRESSION*/
CREATE TABLE GENDER_EXPRESSION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE GENDER_EXPRESSION ADD CONSTRAINT PK_GENDER_EXPRESSION PRIMARY KEY (ID);
ALTER TABLE GENDER_EXPRESSION ADD CONSTRAINT UQ_GEN_EXP_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE GENDER_EXPRESSION IS 'TABLE TO STORE GENDER EXPRESSION VALUES.';
COMMENT ON COLUMN GENDER_EXPRESSION.ID IS 'UNIQUE IDENTIFIER FOR THE GENDER EXPRESSION.';
COMMENT ON COLUMN GENDER_EXPRESSION.DESCRIPTION IS 'DESCRIPTION OF THE GENDER EXPRESSION.';

CREATE GENERATOR SQ_GENDER_EXPRESSION;

COMMENT ON GENERATOR SQ_GENDER_EXPRESSION IS 'GENERATOR FOR TABLE GENDER_EXPRESSION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_GENDER_EXPRESSION
FOR GENDER_EXPRESSION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_GENDER_EXPRESSION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_GENDER_EXPRESSION IS 'TRIGGER FOR TABLE GENDER_EXPRESSION COLUMN ID.';

INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('MASCULINA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('FEMININA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('ANDROGINA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('FLUIDA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('NAO BINARIA');

COMMIT WORK;

/*GENDER_IDENTITY*/
CREATE TABLE GENDER_IDENTITY (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE GENDER_IDENTITY ADD CONSTRAINT PK_GENDER_IDENTITY PRIMARY KEY (ID);
ALTER TABLE GENDER_IDENTITY ADD CONSTRAINT UQ_GEN_IDE_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE GENDER_IDENTITY IS 'TABLE TO STORE GENDER IDENTITY VALUES.';
COMMENT ON COLUMN GENDER_IDENTITY.ID IS 'UNIQUE IDENTIFIER FOR THE GENDER IDENTITY.';
COMMENT ON COLUMN GENDER_IDENTITY.DESCRIPTION IS 'DESCRIPTION OF THE GENDER IDENTITY.';

CREATE GENERATOR SQ_GENDER_IDENTITY;

COMMENT ON GENERATOR SQ_GENDER_IDENTITY IS 'GENERATOR FOR TABLE GENDER_IDENTITY COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_GENDER_IDENTITY
FOR GENDER_IDENTITY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_GENDER_IDENTITY;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_GENDER_IDENTITY IS 'TRIGGER FOR TABLE GENDER_IDENTITY COLUMN ID.';

INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('CISGENERO');
INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('TRANSGENERO');
INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('INTERSEXUAL');

COMMIT WORK;

/*SEXUAL_ORIENTATION*/
CREATE TABLE SEXUAL_ORIENTATION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE SEXUAL_ORIENTATION ADD CONSTRAINT PK_SEXUAL_ORIENTATION PRIMARY KEY (ID);
ALTER TABLE SEXUAL_ORIENTATION ADD CONSTRAINT UQ_SEX_ORI_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE SEXUAL_ORIENTATION IS 'TABLE TO STORE SEXUAL ORIENTATION VALUES.';
COMMENT ON COLUMN SEXUAL_ORIENTATION.ID IS 'UNIQUE IDENTIFIER FOR THE SEXUAL ORIENTATION.';
COMMENT ON COLUMN SEXUAL_ORIENTATION.DESCRIPTION IS 'DESCRIPTION OF THE SEXUAL ORIENTATION.';

CREATE GENERATOR SQ_SEXUAL_ORIENTATION;

COMMENT ON GENERATOR SQ_SEXUAL_ORIENTATION IS 'GENERATOR FOR TABLE SEXUAL_ORIENTATION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_SEXUAL_ORIENTATION
FOR SEXUAL_ORIENTATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_SEXUAL_ORIENTATION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_SEXUAL_ORIENTATION IS 'TRIGGER FOR TABLE SEXUAL_ORIENTATION COLUMN ID.';

INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('HETEROSSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('HOMOSSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('BISSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('ASSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('PANSEXUAL');

COMMIT WORK;

/*MARITAL_STATUS*/
CREATE TABLE MARITAL_STATUS (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE MARITAL_STATUS ADD CONSTRAINT PK_MARITAL_STATUS PRIMARY KEY (ID);
ALTER TABLE MARITAL_STATUS ADD CONSTRAINT UQ_MAR_STA_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE MARITAL_STATUS IS 'TABLE TO STORE MARITAL STATUS VALUES.';
COMMENT ON COLUMN MARITAL_STATUS.ID IS 'UNIQUE IDENTIFIER FOR THE MARITAL STATUS.';
COMMENT ON COLUMN MARITAL_STATUS.DESCRIPTION IS 'DESCRIPTION OF THE MARITAL STATUS.';

CREATE GENERATOR SQ_MARITAL_STATUS;

COMMENT ON GENERATOR SQ_MARITAL_STATUS IS 'GENERATOR FOR TABLE MARITAL_STATUS COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_MARITAL_STATUS
FOR MARITAL_STATUS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_MARITAL_STATUS;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_MARITAL_STATUS IS 'TRIGGER FOR TABLE MARITAL_STATUS COLUMN ID.';

INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('SOLTEIRO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('CASADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('SEPARADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('DIVORCIADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('VIUVO');

COMMIT WORK;

/*RELIGIOUS_AFFILIATION*/
CREATE TABLE RELIGIOUS_AFFILIATION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE RELIGIOUS_AFFILIATION ADD CONSTRAINT PK_RELIGIOUS_AFFILIATION PRIMARY KEY (ID);
ALTER TABLE RELIGIOUS_AFFILIATION ADD CONSTRAINT UQ_REL_AFF_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE RELIGIOUS_AFFILIATION IS 'TABLE TO STORE RELIGIOUS AFFILIATION VALUES.';
COMMENT ON COLUMN RELIGIOUS_AFFILIATION.ID IS 'UNIQUE IDENTIFIER FOR THE RELIGIOUS AFFILIATION.';
COMMENT ON COLUMN RELIGIOUS_AFFILIATION.DESCRIPTION IS 'DESCRIPTION OF THE RELIGIOUS AFFILIATION.';

CREATE GENERATOR SQ_RELIGIOUS_AFFILIATION;

COMMENT ON GENERATOR SQ_RELIGIOUS_AFFILIATION IS 'GENERATOR FOR TABLE RELIGIOUS_AFFILIATION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_RELIGIOUS_AFFILIATION
FOR RELIGIOUS_AFFILIATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_RELIGIOUS_AFFILIATION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_RELIGIOUS_AFFILIATION IS 'TRIGGER FOR TABLE RELIGIOUS_AFFILIATION COLUMN ID.';

INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CRISTIANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CATOLICISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('PROTESTANTISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ADVENTISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ANGLICANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('TESTEMUNHA DE JEOVA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('MORMONISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('IGREJA ORTODOXA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ESPIRITISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ISLAMISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('JUDAISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('NEOPAGANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('HINDUISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('SANTO DAIME');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CANDOMBLE');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('UMBANDA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('AGNOSTICISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ATEISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('SEM RELIGIAO');

COMMIT WORK;

/*JOB_OCCUPATION*/
CREATE TABLE JOB_OCCUPATION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE JOB_OCCUPATION ADD CONSTRAINT PK_JOB_OCCUPATION PRIMARY KEY (ID);
ALTER TABLE JOB_OCCUPATION ADD CONSTRAINT UQ_JOB_OCC_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE JOB_OCCUPATION IS 'TABLE TO STORE JOB OCCUPATION VALUES.';
COMMENT ON COLUMN JOB_OCCUPATION.ID IS 'UNIQUE IDENTIFIER FOR THE JOB OCCUPATION.';
COMMENT ON COLUMN JOB_OCCUPATION.DESCRIPTION IS 'DESCRIPTION OF THE JOB OCCUPATION.';

CREATE GENERATOR SQ_JOB_OCCUPATION;

COMMENT ON GENERATOR SQ_JOB_OCCUPATION IS 'GENERATOR FOR TABLE JOB_OCCUPATION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_JOB_OCCUPATION
FOR JOB_OCCUPATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_JOB_OCCUPATION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_JOB_OCCUPATION IS 'TRIGGER FOR TABLE JOB_OCCUPATION COLUMN ID.';

INSERT INTO JOB_OCCUPATION (DESCRIPTION) VALUES ('DESEMPREGADO');

COMMIT WORK;

/*ETHNIC_GROUP*/
CREATE TABLE ETHNIC_GROUP (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE ETHNIC_GROUP ADD CONSTRAINT PK_ETHNIC_GROUP PRIMARY KEY (ID);
ALTER TABLE ETHNIC_GROUP ADD CONSTRAINT UQ_ETH_GRO_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE ETHNIC_GROUP IS 'TABLE TO STORE ETHNIC GROUP VALUES.';
COMMENT ON COLUMN ETHNIC_GROUP.ID IS 'UNIQUE IDENTIFIER FOR THE ETHNIC GROUP.';
COMMENT ON COLUMN ETHNIC_GROUP.DESCRIPTION IS 'DESCRIPTION OF THE ETHNIC GROUP.';

CREATE GENERATOR SQ_ETHNIC_GROUP;

COMMENT ON GENERATOR SQ_ETHNIC_GROUP IS 'GENERATOR FOR TABLE ETHNIC_GROUP COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_ETHNIC_GROUP
FOR ETHNIC_GROUP
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_ETHNIC_GROUP;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_ETHNIC_GROUP IS 'TRIGGER FOR TABLE ETHNIC_GROUP COLUMN ID.';

INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('BRANCO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('PARDO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('NEGRO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('INDIGENA');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('AMARELO');

COMMIT WORK;

/*COUNTRY_GEOGRAPHIC*/
CREATE TABLE COUNTRY_GEOGRAPHIC (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE COUNTRY_GEOGRAPHIC ADD CONSTRAINT PK_COUNTRY_GEOGRAPHIC PRIMARY KEY (ID);
ALTER TABLE COUNTRY_GEOGRAPHIC ADD CONSTRAINT UQ_COU_GEO_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE COUNTRY_GEOGRAPHIC IS 'TABLE TO STORE COUNTRY GEOGRAPHIC VALUES.';
COMMENT ON COLUMN COUNTRY_GEOGRAPHIC.ID IS 'UNIQUE IDENTIFIER FOR THE COUNTRY GEOGRAPHIC.';
COMMENT ON COLUMN COUNTRY_GEOGRAPHIC.DESCRIPTION IS 'DESCRIPTION OF THE COUNTRY GEOGRAPHIC.';

CREATE GENERATOR SQ_COUNTRY_GEOGRAPHIC;

COMMENT ON GENERATOR SQ_COUNTRY_GEOGRAPHIC IS 'GENERATOR FOR TABLE COUNTRY_GEOGRAPHIC COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_COUNTRY_GEOGRAPHIC
FOR COUNTRY_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_COUNTRY_GEOGRAPHIC;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_COUNTRY_GEOGRAPHIC IS 'TRIGGER FOR TABLE COUNTRY_GEOGRAPHIC COLUMN ID.';

INSERT INTO COUNTRY_GEOGRAPHIC (DESCRIPTION) VALUES ('BRASIL');

COMMIT WORK;

/*STATE_GEOGRAPHIC*/
CREATE TABLE STATE_GEOGRAPHIC (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL,
    ID_COUNTRY INT NOT NULL
);

ALTER TABLE STATE_GEOGRAPHIC ADD CONSTRAINT PK_STATE_GEOGRAPHIC PRIMARY KEY (ID);
ALTER TABLE STATE_GEOGRAPHIC ADD CONSTRAINT FK_STATE_COUNTRY FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRY_GEOGRAPHIC(ID);
ALTER TABLE STATE_GEOGRAPHIC ADD CONSTRAINT UQ_STA_GEO_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE STATE_GEOGRAPHIC IS 'TABLE TO STORE STATE GEOGRAPHIC VALUES.';
COMMENT ON COLUMN STATE_GEOGRAPHIC.ID IS 'UNIQUE IDENTIFIER FOR THE STATE GEOGRAPHIC.';
COMMENT ON COLUMN STATE_GEOGRAPHIC.DESCRIPTION IS 'DESCRIPTION OF THE STATE GEOGRAPHIC.';
COMMENT ON COLUMN STATE_GEOGRAPHIC.ID_COUNTRY IS 'FOREIGN KEY COUNTRY_GEOGRAPHIC(ID).';

CREATE GENERATOR SQ_STATE_GEOGRAPHIC;

COMMENT ON GENERATOR SQ_STATE_GEOGRAPHIC IS 'GENERATOR FOR TABLE STATE_GEOGRAPHIC COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_STATE_GEOGRAPHIC
FOR STATE_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_STATE_GEOGRAPHIC;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_STATE_GEOGRAPHIC IS 'TRIGGER FOR TABLE STATE_GEOGRAPHIC COLUMN ID.';

INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ACRE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ALAGOAS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('AMAPÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('AMAZONAS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('BAHIA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('CEARÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ESPÍRITO SANTO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('GOIÁS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MARANHÃO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MATO GROSSO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MATO GROSSO DO SUL', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MINAS GERAIS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARAÍBA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARANÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PERNAMBUCO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PIAUÍ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO DE JANEIRO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO GRANDE DO NORTE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO GRANDE DO SUL', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RONDÔNIA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RORAIMA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SANTA CATARINA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SÃO PAULO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SERGIPE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('TOCANTINS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('DISTRITO FEDERAL', 1);

COMMIT WORK;

/*CITY_GEOGRAPHIC*/
CREATE TABLE CITY_GEOGRAPHIC (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(80) NOT NULL,
    ID_STATE INT NOT NULL
);

ALTER TABLE CITY_GEOGRAPHIC ADD CONSTRAINT PK_CITY_GEOGRAPHIC PRIMARY KEY (ID);
ALTER TABLE CITY_GEOGRAPHIC ADD CONSTRAINT FK_CITY_STATE FOREIGN KEY (ID_STATE) REFERENCES STATE_GEOGRAPHIC(ID);

COMMENT ON TABLE CITY_GEOGRAPHIC IS 'TABLE TO STORE CITY GEOGRAPHIC VALUES.';
COMMENT ON COLUMN CITY_GEOGRAPHIC.ID IS 'UNIQUE IDENTIFIER FOR THE CITY GEOGRAPHIC.';
COMMENT ON COLUMN CITY_GEOGRAPHIC.DESCRIPTION IS 'DESCRIPTION OF THE CITY GEOGRAPHIC.';
COMMENT ON COLUMN CITY_GEOGRAPHIC.ID_STATE IS 'FOREIGN KEY STATE_GEOGRAPHIC(ID).';

CREATE GENERATOR SQ_CITY_GEOGRAPHIC;

COMMENT ON GENERATOR SQ_CITY_GEOGRAPHIC IS 'GENERATOR FOR TABLE CITY_GEOGRAPHIC COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_CITY_GEOGRAPHIC
FOR CITY_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_CITY_GEOGRAPHIC;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_CITY_GEOGRAPHIC IS 'TRIGGER FOR TABLE CITY_GEOGRAPHIC COLUMN ID.';

INSERT INTO CITY_GEOGRAPHIC (DESCRIPTION, ID_STATE) VALUES ('ARACATUBA', 24);

COMMIT WORK;

/*LABOR_POSITION*/
CREATE TABLE LABOR_POSITION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE LABOR_POSITION ADD CONSTRAINT PK_LABOR_POSITION PRIMARY KEY (ID);
ALTER TABLE LABOR_POSITION ADD CONSTRAINT UQ_LAB_POS_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE LABOR_POSITION IS 'TABLE TO STORE LABOR POSITION VALUES.';
COMMENT ON COLUMN LABOR_POSITION.ID IS 'UNIQUE IDENTIFIER FOR THE LABOR POSITION.';
COMMENT ON COLUMN LABOR_POSITION.DESCRIPTION IS 'DESCRIPTION OF THE LABOR POSITION.';

CREATE GENERATOR SQ_LABOR_POSITION;

COMMENT ON GENERATOR SQ_LABOR_POSITION IS 'GENERATOR FOR TABLE LABOR_POSITION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_LABOR_POSITION
FOR LABOR_POSITION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_LABOR_POSITION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_LABOR_POSITION IS 'TRIGGER FOR TABLE LABOR_POSITION COLUMN ID.';

INSERT INTO LABOR_POSITION (DESCRIPTION) VALUES ('ADMINISTRATIVO');
INSERT INTO LABOR_POSITION (DESCRIPTION) VALUES ('FINANCEIRO');
INSERT INTO LABOR_POSITION (DESCRIPTION) VALUES ('RECURSOS HUMANOS');
INSERT INTO LABOR_POSITION (DESCRIPTION) VALUES ('CONTABILIDADE');
INSERT INTO LABOR_POSITION (DESCRIPTION) VALUES ('COMERCIAL');

COMMIT WORK;

/*FINANCIAL_INSTITUTION*/
CREATE TABLE FINANCIAL_INSTITUTION (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL,
    COMPENSATION INT NOT NULL
);

ALTER TABLE FINANCIAL_INSTITUTION ADD CONSTRAINT PK_FINANCIAL_INSTITUTION PRIMARY KEY (ID);
ALTER TABLE FINANCIAL_INSTITUTION ADD CONSTRAINT UQ_FIN_INS_DESCRIPTION UNIQUE (DESCRIPTION);
ALTER TABLE FINANCIAL_INSTITUTION ADD CONSTRAINT UQ_FIN_INS_COMPENSATION UNIQUE (COMPENSATION);

COMMENT ON TABLE FINANCIAL_INSTITUTION IS 'TABLE TO STORE FINANCIAL INSTITUTIONS VALUES.';
COMMENT ON COLUMN FINANCIAL_INSTITUTION.ID IS 'UNIQUE IDENTIFIER FOR THE FINANCIAL INSTITUTION.';
COMMENT ON COLUMN FINANCIAL_INSTITUTION.DESCRIPTION IS 'DESCRIPTION OF THE FINANCIAL INSTITUTION.';
COMMENT ON COLUMN FINANCIAL_INSTITUTION.COMPENSATION IS 'COMPENSATION NUMBER OF THE FINANCIAL INSTITUTION.';

CREATE GENERATOR SQ_FINANCIAL_INSTITUTION;

COMMENT ON GENERATOR SQ_FINANCIAL_INSTITUTION IS 'GENERATOR FOR TABLE FINANCIAL_INSTITUTION COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_FINANCIAL_INSTITUTION
FOR FINANCIAL_INSTITUTION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_FINANCIAL_INSTITUTION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_FINANCIAL_INSTITUTION IS 'TRIGGER FOR TABLE FINANCIAL_INSTITUTION COLUMN ID.';

INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('CAIXA ECONOMICA FEDERAL', 104);
INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('BRADESCO', 237);
INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('ITAU', 341);
INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('SANTANDER', 33);
INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('SICOOB', 756);
INSERT INTO FINANCIAL_INSTITUTION (DESCRIPTION, COMPENSATION) VALUES ('SICREDI', 748);

COMMIT WORK;

/*DOCUMENT_TYPE*/
CREATE TABLE DOCUMENT_TYPE (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE DOCUMENT_TYPE ADD CONSTRAINT PK_DOCUMENT_TYPE PRIMARY KEY (ID);
ALTER TABLE DOCUMENT_TYPE ADD CONSTRAINT UQ_DOC_TYP_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE DOCUMENT_TYPE IS 'TABLE TO STORE DOCUMENT TYPE VALUES.';
COMMENT ON COLUMN DOCUMENT_TYPE.ID IS 'UNIQUE IDENTIFIER FOR THE DOCUMENT TYPE.';
COMMENT ON COLUMN DOCUMENT_TYPE.DESCRIPTION IS 'DESCRIPTION OF THE DOCUMENT TYPE.';

CREATE GENERATOR SQ_DOCUMENT_TYPE;

COMMENT ON GENERATOR SQ_DOCUMENT_TYPE IS 'GENERATOR FOR TABLE DOCUMENT_TYPE COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_DOCUMENT_TYPE
FOR DOCUMENT_TYPE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_DOCUMENT_TYPE;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_DOCUMENT_TYPE IS 'TRIGGER FOR TABLE DOCUMENT_TYPE COLUMN ID.';

INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('REGISTRO GERAL');
INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('CADASTRO NACIONAL DE PESSOA FISICA');
INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('CARTEIRA NACIONAL DE HABILITACAO');

INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('CADASTRO NACIONAL DE PESSOA JURIDICA');
INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('INSCRICAO ESTADUAL');
INSERT INTO DOCUMENT_TYPE (DESCRIPTION) VALUES ('INSCRICAO MUNICIPAL');

COMMIT WORK;

/*REGISTRATION_STATUS*/
CREATE TABLE REGISTRATION_STATUS (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE REGISTRATION_STATUS ADD CONSTRAINT PK_REGISTRATION_STATUS PRIMARY KEY (ID);
ALTER TABLE REGISTRATION_STATUS ADD CONSTRAINT UQ_REG_STA_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE REGISTRATION_STATUS IS 'TABLE TO STORE REGISTRATION STATUS VALUES.';
COMMENT ON COLUMN REGISTRATION_STATUS.ID IS 'UNIQUE IDENTIFIER FOR THE REGISTRATION STATUS.';
COMMENT ON COLUMN REGISTRATION_STATUS.DESCRIPTION IS 'DESCRIPTION OF THE REGISTRATION STATUS.';

CREATE GENERATOR SQ_REGISTRATION_STATUS;

COMMENT ON GENERATOR SQ_REGISTRATION_STATUS IS 'GENERATOR FOR TABLE REGISTRATION_STATUS COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_REGISTRATION_STATUS
FOR REGISTRATION_STATUS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_REGISTRATION_STATUS;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_REGISTRATION_STATUS IS 'TRIGGER FOR TABLE REGISTRATION_STATUS COLUMN ID.';

INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('ATIVO');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('INATIVO');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('C PENDENCIA FINANCEIRA');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('C PENDENCIA ADMINISTRATIVA');

COMMIT WORK;

/*PUBLIC_PLACE*/
CREATE TABLE PUBLIC_PLACE (
    ID INT NOT NULL,
    DESCRIPTION VARCHAR(45) NOT NULL
);

ALTER TABLE PUBLIC_PLACE ADD CONSTRAINT PK_PUBLIC_PLACE PRIMARY KEY (ID);
ALTER TABLE PUBLIC_PLACE ADD CONSTRAINT UQ_PUB_PLA_DESCRIPTION UNIQUE (DESCRIPTION);

COMMENT ON TABLE PUBLIC_PLACE IS 'TABLE TO STORE PUBLIC PLACE VALUES.';
COMMENT ON COLUMN PUBLIC_PLACE.ID IS 'UNIQUE IDENTIFIER FOR THE PUBLIC PLACE.';
COMMENT ON COLUMN PUBLIC_PLACE.DESCRIPTION IS 'DESCRIPTION OF THE PUBLIC PLACE.';

CREATE GENERATOR SQ_PUBLIC_PLACE;

COMMENT ON GENERATOR SQ_PUBLIC_PLACE IS 'GENERATOR FOR TABLE PUBLIC_PLACE COLUMN ID.';

SET TERM ^ ;
CREATE TRIGGER BI_PUBLIC_PLACE
FOR PUBLIC_PLACE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_PUBLIC_PLACE;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_PUBLIC_PLACE IS 'TRIGGER FOR TABLE PUBLIC_PLACE COLUMN ID.';

INSERT INTO PUBLIC_PLACE (DESCRIPTION) VALUES ('RUA');
INSERT INTO PUBLIC_PLACE (DESCRIPTION) VALUES ('AVENIDA');
INSERT INTO PUBLIC_PLACE (DESCRIPTION) VALUES ('RODOVIA');

COMMIT WORK;

/*CUSTOMER_REGISTRATION*/
CREATE TABLE CUSTOMER_REGISTRATION (
    ID INT NOT NULL,

    NAME_BIOLOGICAL VARCHAR(150) NOT NULL,
    NAME_SOCIAL VARCHAR(150),

    DOCUMENT_RG VARCHAR(25),
    DOCUMENT_CPF VARCHAR(25),

    ID_BIOLOGICAL_SEX INT,
    ID_SEXUAL_ORIENTATION INT,
    ID_GENDER_EXPRESSION INT,
    ID_GENDER_IDENTITY INT,

    ID_ETHNIC_GROUP INT,
    ID_JOB_OCCUPATION INT,
    ID_MARITAL_STATUS INT,
    ID_RELIGIOUS_AFFILIATION INT,

    ID_REGISTRATION_STATUS INT,

    OBSERVATION VARCHAR(255)
);

ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT PK_CUSTOMER_REGISTRATION PRIMARY KEY (ID);

COMMENT ON TABLE CUSTOMER_REGISTRATION IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.NAME_BIOLOGICAL IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.NAME_SOCIAL IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.DOCUMENT_RG IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.DOCUMENT_CPF IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_BIOLOGICAL_SEX IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_SEXUAL_ORIENTATION IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_GENDER_EXPRESSION IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_GENDER_IDENTITY IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_ETHNIC_GROUP IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_JOB_OCCUPATION IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_MARITAL_STATUS IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_RELIGIOUS_AFFILIATION IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.ID_REGISTRATION_STATUS IS '';
COMMENT ON COLUMN CUSTOMER_REGISTRATION.OBSERVATION IS '';

CREATE GENERATOR SQ_CUSTOMER_REGISTRATION;

COMMENT ON GENERATOR SQ_CUSTOMER_REGISTRATION IS 'GENERATOR FOR TABLE CUSTOMER_REGISTRATION COLUMN ID.';

ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_BIOLOGICAL
FOREIGN KEY (ID_BIOLOGICAL_SEX) REFERENCES BIOLOGICAL_SEX(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_SEXUAL
FOREIGN KEY (ID_SEXUAL_ORIENTATION) REFERENCES SEXUAL_ORIENTATION(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_GENDER_E
FOREIGN KEY (ID_GENDER_EXPRESSION) REFERENCES GENDER_EXPRESSION(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_GENDER_I
FOREIGN KEY (ID_GENDER_IDENTITY) REFERENCES GENDER_IDENTITY(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_ETHNIC
FOREIGN KEY (ID_ETHNIC_GROUP) REFERENCES ETHNIC_GROUP(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_JOB
FOREIGN KEY (ID_JOB_OCCUPATION) REFERENCES JOB_OCCUPATION(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_MARITAL
FOREIGN KEY (ID_MARITAL_STATUS) REFERENCES MARITAL_STATUS(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_RELIGIOUS
FOREIGN KEY (ID_RELIGIOUS_AFFILIATION) REFERENCES RELIGIOUS_AFFILIATION(ID);
ALTER TABLE CUSTOMER_REGISTRATION ADD CONSTRAINT FK_CUSTOMER_REGISTRATION
FOREIGN KEY (ID_REGISTRATION_STATUS) REFERENCES REGISTRATION_STATUS(ID);

SET TERM ^ ;
CREATE TRIGGER BI_CUSTOMER_REGISTRATION
FOR CUSTOMER_REGISTRATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_CUSTOMER_REGISTRATION;
END^
SET TERM ; ^

COMMENT ON TRIGGER BI_CUSTOMER_REGISTRATION IS 'TRIGGER FOR TABLE CUSTOMER_REGISTRATION COLUMN ID.';

COMMIT WORK;

/*
RESIDENTIAL_ADDRESS
CREATE TABLE RESIDENTIAL_ADDRESS (
    ID INT NOT NULL PRIMARY KEY,
    ID_CUSTOMER_DATA INT NOT NULL UNIQUE,

    ID_PUBLIC_PLACE INT,
    ADDRESS VARCHAR(150),
    NUMBER VARCHAR(8),
    NEIGHBORHOOD VARCHAR(75),
    CEP VARCHAR(15),
    COMPLEMENT VARCHAR(75),

    PHONE_DDD CHAR(2),
    PHONE_NUMBER VARCHAR(10),

    MAIL VARCHAR(75),

    OBSERVATION VARCHAR(255)
);
*/

/*CUSTOMER_FAMILY*/



/*
SUPPLIER_REGISTRATION
EMPLOYEE_REGISTRATION
*/










