CREATE TABLE METADATA(
    ID INTEGER,
    NAME VARCHAR(65),
    COMMENT VARCHAR(255),

    CONSTRAINT PK_METADATA_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_METADATA_NAME UNIQUE (NAME),
    CONSTRAINT NN_METADATA_NAME CHECK (NAME IS NOT NULL)
);

CREATE GENERATOR SQ_METADATA_ID;

SET TERM ^ ;
CREATE TRIGGER BI_METADATA_ID
FOR METADATA
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_METADATA_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('METADATA', 'TABLE TO STORE METADATA.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_METADATA_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE METADATA COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_METADATA_NAME', 'UNIQUE CONSTRAINT FOR TABLE METADATA COLUMN NAME.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_METADATA_NAME', 'NOT NULL CONSTRAINT FOR TABLE METADATA COLUMN NAME.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_METADATA_ID', 'GENERATOR FOR TABLE METADATA COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_METADATA_ID', 'TRIGGER FOR TABLE METADATA COLUMN ID.');

COMMIT WORK;

CREATE TABLE BIOLOGICAL_SEX (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_BIOLOGICAL_SEX_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_BIOLOGICAL_SEX_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_BIOLOGICAL_SEX_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_BIOLOGICAL_SEX_ID;

SET TERM ^ ;
CREATE TRIGGER BI_BIOLOGICAL_SEX_ID
FOR BIOLOGICAL_SEX
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_BIOLOGICAL_SEX_ID;
END^
SET TERM ; ^

INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('MASCULINO');
INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('FEMININO');
INSERT INTO BIOLOGICAL_SEX (DESCRIPTION) VALUES ('INTERSEXO');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('BIOLOGICAL_SEX', 'TABLE TO STORE BIOLOGICAL SEX VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_BIOLOGICAL_SEX_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE BIOLOGICAL_SEX COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_BIOLOGICAL_SEX_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE BIOLOGICAL_SEX COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_BIOLOGICAL_SEX_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE BIOLOGICAL_SEX COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_BIOLOGICAL_SEX_ID', 'GENERATOR FOR TABLE BIOLOGICAL_SEX COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_BIOLOGICAL_SEX_ID', 'TRIGGER FOR TABLE BIOLOGICAL_SEX COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('BIOLOGICAL_SEX.ID', 'UNIQUE IDENTIFIER FOR THE BIOLOGICAL SEX.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BIOLOGICAL_SEX.DESCRIPTION', 'DESCRIPTION OF THE BIOLOGICAL SEX.');

COMMIT WORK;

CREATE TABLE GENDER_EXPRESSION (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_GENDER_EXPRESSION_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_GENDER_EXPRESSION_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_GENDER_EXPRESSION_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_GENDER_EXPRESSION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_GENDER_EXPRESSION_ID
FOR GENDER_EXPRESSION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_GENDER_EXPRESSION_ID;
END^
SET TERM ; ^

INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('MASCULINA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('FEMININA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('ANDROGINA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('FLUIDA');
INSERT INTO GENDER_EXPRESSION (DESCRIPTION) VALUES ('NAO BINARIA');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_EXPRESSION', 'TABLE TO STORE GENDER EXPRESSION VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_GENDER_EXPRESSION_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE GENDER_EXPRESSION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_GENDER_EXPRESSION_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE GENDER_EXPRESSION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_GENDER_EXPRESSION_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE GENDER_EXPRESSION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_GENDER_EXPRESSION_ID', 'GENERATOR FOR TABLE GENDER_EXPRESSION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_GENDER_EXPRESSION_ID', 'TRIGGER FOR TABLE GENDER_EXPRESSION COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_EXPRESSION.ID', 'UNIQUE IDENTIFIER FOR THE GENDER EXPRESSION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_EXPRESSION.DESCRIPTION', 'DESCRIPTION OF THE GENDER EXPRESSION.');

COMMIT WORK;

CREATE TABLE GENDER_IDENTITY (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_GENDER_IDENTITY_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_GENDER_IDENTITY_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_GENDER_IDENTITY_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_GENDER_IDENTITY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_GENDER_IDENTITY_ID
FOR GENDER_IDENTITY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_GENDER_IDENTITY_ID;
END^
SET TERM ; ^

INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('CISGENERO');
INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('TRANSGENERO');
INSERT INTO GENDER_IDENTITY (DESCRIPTION) VALUES ('INTERSEXUAL');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_IDENTITY', 'TABLE TO STORE GENDER IDENTITY VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_GENDER_IDENTITY_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE GENDER_IDENTITY COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_GENDER_IDENTITY_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE GENDER_IDENTITY COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_GENDER_IDENTITY_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE GENDER_IDENTITY COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_GENDER_IDENTITY_ID', 'GENERATOR FOR TABLE GENDER_IDENTITY COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_GENDER_IDENTITY_ID', 'TRIGGER FOR TABLE GENDER_IDENTITY COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_IDENTITY.ID', 'UNIQUE IDENTIFIER FOR THE GENDER IDENTITY.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('GENDER_IDENTITY.DESCRIPTION', 'DESCRIPTION OF THE GENDER IDENTITY.');

COMMIT WORK;

CREATE TABLE SEXUAL_ORIENTATION (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_SEXUAL_ORIENTATION_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_SEXUAL_ORIENTATION_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_SEXUAL_ORIENTATION_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_SEXUAL_ORIENTATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_SEXUAL_ORIENTATION_ID
FOR SEXUAL_ORIENTATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_SEXUAL_ORIENTATION_ID;
END^
SET TERM ; ^

INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('HETEROSSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('HOMOSSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('BISSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('ASSEXUAL');
INSERT INTO SEXUAL_ORIENTATION (DESCRIPTION) VALUES ('PANSEXUAL');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('SEXUAL_ORIENTATION', 'TABLE TO STORE SEXUAL ORIENTATION VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_SEXUAL_ORIENTATION_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE SEXUAL_ORIENTATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_SEXUAL_ORIENTATION_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE SEXUAL_ORIENTATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_SEXUAL_ORIENTATION_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE SEXUAL_ORIENTATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_SEXUAL_ORIENTATION_ID', 'GENERATOR FOR TABLE SEXUAL_ORIENTATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_SEXUAL_ORIENTATION_ID', 'TRIGGER FOR TABLE SEXUAL_ORIENTATION COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('SEXUAL_ORIENTATION.ID', 'UNIQUE IDENTIFIER FOR THE SEXUAL ORIENTATION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SEXUAL_ORIENTATION.DESCRIPTION', 'DESCRIPTION OF THE SEXUAL ORIENTATION.');

COMMIT WORK;

CREATE TABLE MARITAL_STATUS (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_MARITAL_STATUS_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_MARITAL_STATUS_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_MARITAL_STATUS_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_MARITAL_STATUS_ID;

SET TERM ^ ;
CREATE TRIGGER BI_MARITAL_STATUS_ID
FOR MARITAL_STATUS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_MARITAL_STATUS_ID;
END^
SET TERM ; ^

INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('SOLTEIRO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('CASADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('SEPARADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('DIVORCIADO');
INSERT INTO MARITAL_STATUS (DESCRIPTION) VALUES ('VIUVO');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('MARITAL_STATUS', 'TABLE TO STORE MARITAL STATUS VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_MARITAL_STATUS_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE MARITAL_STATUS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_MARITAL_STATUS_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE MARITAL_STATUS COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_MARITAL_STATUS_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE MARITAL_STATUS COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_MARITAL_STATUS_ID', 'GENERATOR FOR TABLE MARITAL_STATUS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_MARITAL_STATUS_ID', 'TRIGGER FOR TABLE MARITAL_STATUS COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('MARITAL_STATUS.ID', 'UNIQUE IDENTIFIER FOR THE MARITAL STATUS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('MARITAL_STATUS.DESCRIPTION', 'DESCRIPTION OF THE MARITAL STATUS.');

COMMIT WORK;

CREATE TABLE RELIGIOUS_AFFILIATION (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_RELIGIOUS_AFFILIATION_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_RELIGIOUS_AFFILIATION_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_RELIGIOUS_AFFILIATION_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_RELIGIOUS_AFFILIATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_RELIGIOUS_AFFILIATION_ID
FOR RELIGIOUS_AFFILIATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_RELIGIOUS_AFFILIATION_ID;
END^
SET TERM ; ^

INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CRISTIANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CATOLICISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('PROTESTANTISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ADVENTISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ANGLICANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('TESTEMUNHA DE JEOVA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('MORMONISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('IGREJA ORTODOXA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ESPIRITISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ISLAMISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('JUDAISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('NEOPAGANISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('HINDUISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('SANTO DAIME');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('CANDOMBLE');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('UMBANDA');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('AGNOSTICISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('ATEISMO');
INSERT INTO RELIGIOUS_AFFILIATION (DESCRIPTION) VALUES ('SEM RELIGIAO');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('RELIGIOUS_AFFILIATION', 'TABLE TO STORE RELIGIOUS AFFILIATION VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_RELIGIOUS_AFFILIATION_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE RELIGIOUS_AFFILIATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_RELIGIOUS_AFFILIATION_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE RELIGIOUS_AFFILIATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_RELIGIOUS_AFFILIATION_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE RELIGIOUS_AFFILIATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_RELIGIOUS_AFFILIATION_ID', 'GENERATOR FOR TABLE RELIGIOUS_AFFILIATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_RELIGIOUS_AFFILIATION_ID', 'TRIGGER FOR TABLE RELIGIOUS_AFFILIATION COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('RELIGIOUS_AFFILIATION.ID', 'UNIQUE IDENTIFIER FOR THE RELIGIOUS AFFILIATION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RELIGIOUS_AFFILIATION.DESCRIPTION', 'DESCRIPTION OF THE RELIGIOUS AFFILIATION.');

COMMIT WORK;

CREATE TABLE JOB_OCCUPATION (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_JOB_OCCUPATION_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_JOB_OCCUPATION_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_JOB_OCCUPATION_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_JOB_OCCUPATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_JOB_OCCUPATION_ID
FOR JOB_OCCUPATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_JOB_OCCUPATION_ID;
END^
SET TERM ; ^

INSERT INTO JOB_OCCUPATION (DESCRIPTION) VALUES ('DESEMPREGADO');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('JOB_OCCUPATION', 'TABLE TO STORE JOB OCCUPATION VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_JOB_OCCUPATION_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE JOB_OCCUPATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_JOB_OCCUPATION_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE JOB_OCCUPATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_JOB_OCCUPATION_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE JOB_OCCUPATION COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_JOB_OCCUPATION_ID', 'GENERATOR FOR TABLE JOB_OCCUPATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_JOB_OCCUPATION_ID', 'TRIGGER FOR TABLE JOB_OCCUPATION COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('JOB_OCCUPATION.ID', 'UNIQUE IDENTIFIER FOR THE JOB OCCUPATION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('JOB_OCCUPATION.DESCRIPTION', 'DESCRIPTION OF THE JOB OCCUPATION.');

COMMIT WORK;

CREATE TABLE ETHNIC_GROUP (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_ETHNIC_GROUP_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_ETHNIC_GROUP_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_ETHNIC_GROUP_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_ETHNIC_GROUP_ID;

SET TERM ^ ;
CREATE TRIGGER BI_ETHNIC_GROUP_ID
FOR ETHNIC_GROUP
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_ETHNIC_GROUP_ID;
END^
SET TERM ; ^

INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('BRANCO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('PARDO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('NEGRO');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('INDIGENA');
INSERT INTO ETHNIC_GROUP (DESCRIPTION) VALUES ('AMARELO');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('ETHNIC_GROUP', 'TABLE TO STORE ETHNIC GROUP VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_ETHNIC_GROUP_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE ETHNIC_GROUP COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_ETHNIC_GROUP_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE ETHNIC_GROUP COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_ETHNIC_GROUP_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE ETHNIC_GROUP COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_ETHNIC_GROUP_ID', 'GENERATOR FOR TABLE ETHNIC_GROUP COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_ETHNIC_GROUP_ID', 'TRIGGER FOR TABLE ETHNIC_GROUP COLUMN ID.');
    
INSERT INTO METADATA (NAME, COMMENT) VALUES ('ETHNIC_GROUP.ID', 'UNIQUE IDENTIFIER FOR THE ETHNIC GROUP.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('ETHNIC_GROUP.DESCRIPTION', 'DESCRIPTION OF THE ETHNIC GROUP.');

COMMIT WORK;

CREATE TABLE COUNTRY_GEOGRAPHIC (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_COUNTRY_GEOGRAPHIC_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_COUNTRY_GEOGRAPHIC_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_COUNTRY_GEOGRAPHIC_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_COUNTRY_GEOGRAPHIC_ID;

SET TERM ^ ;
CREATE TRIGGER BI_COUNTRY_GEOGRAPHIC_ID
FOR COUNTRY_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_COUNTRY_GEOGRAPHIC_ID;
END^
SET TERM ; ^

INSERT INTO COUNTRY_GEOGRAPHIC (DESCRIPTION) VALUES ('BRASIL');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('COUNTRY_GEOGRAPHIC', 'TABLE TO STORE COUNTRY GEOGRAPHIC VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_COUNTRY_GEOGRAPHIC_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE COUNTRY_GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_COUNTRY_GEOGRAPHIC_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE COUNTRY_GEOGRAPHIC COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_COUNTRY_GEOGRAPHIC_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE COUNTRY_GEOGRAPHIC COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_COUNTRY_GEOGRAPHIC_ID', 'GENERATOR FOR TABLE COUNTRY_GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_COUNTRY_GEOGRAPHIC_ID', 'TRIGGER FOR TABLE COUNTRY_GEOGRAPHIC COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('COUNTRY_GEOGRAPHIC.ID', 'UNIQUE IDENTIFIER FOR THE COUNTRY GEOGRAPHIC.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('COUNTRY_GEOGRAPHIC.DESCRIPTION', 'DESCRIPTION OF THE COUNTRY GEOGRAPHIC.');

COMMIT WORK;

CREATE TABLE STATE_GEOGRAPHIC (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),
    ID_COUNTRY INTEGER,

    CONSTRAINT PK_STATE_GEOGRAPHIC_ID PRIMARY KEY (ID),
    CONSTRAINT NN_STATE_GEOGRAPHIC_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT FK_STATE_GEO_COUNTRY_GEO_ID FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRY_GEOGRAPHIC(ID),
    CONSTRAINT NN_STATE_GEOGRAPHIC_ID_COUNTRY CHECK (ID_COUNTRY IS NOT NULL)
);

CREATE GENERATOR SQ_STATE_GEOGRAPHIC_ID;

SET TERM ^ ;
CREATE TRIGGER BI_STATE_GEOGRAPHIC_ID
FOR STATE_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_STATE_GEOGRAPHIC_ID;
END^
SET TERM ; ^

INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ACRE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ALAGOAS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('AMAPÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('AMAZONAS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('BAHIA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('CEARÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('ESPÍRITO SANTO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('GOIÁS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MARANHÃO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MATO GROSSO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MATO GROSSO DO SUL', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('MINAS GERAIS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARAÍBA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PARANÁ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PERNAMBUCO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('PIAUÍ', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO DE JANEIRO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO GRANDE DO NORTE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RIO GRANDE DO SUL', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RONDÔNIA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('RORAIMA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SANTA CATARINA', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SÃO PAULO', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('SERGIPE', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('TOCANTINS', 1);
INSERT INTO STATE_GEOGRAPHIC (DESCRIPTION, ID_COUNTRY) VALUES ('DISTRITO FEDERAL', 1);

INSERT INTO METADATA (NAME, COMMENT) VALUES ('STATE_GEOGRAPHIC', 'TABLE TO STORE STATE GEOGRAPHIC VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_STATE_GEOGRAPHIC_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE STATE GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_STATE_GEOGRAPHIC_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE STATE GEOGRAPHIC COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_STATE_GEO_COUNTRY_GEO_ID', 'FOREIGN KEY REFERENCES COUNTRY_GEOGRAPHIC (ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_STATE_GEOGRAPHIC_ID_COUNTRY', 'NOT NULL CONSTRAINT FOR TABLE STATE GEOGRAPHIC COLUMN ID_COUNTRY.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_STATE_GEOGRAPHIC_ID', 'GENERATOR FOR TABLE STATE GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_STATE_GEOGRAPHIC_ID', 'TRIGGER FOR TABLE STATE GEOGRAPHIC COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('STATE_GEOGRAPHIC.ID', 'UNIQUE IDENTIFIER FOR THE STATE GEOGRAPHIC.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('STATE_GEOGRAPHIC.DESCRIPTION', 'DESCRIPTION OF THE STATE GEOGRAPHIC.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('STATE_GEOGRAPHIC.ID_COUNTRY', 'FOREIGN KEY COUNTRY_GEOGRAPHIC(ID).');

COMMIT WORK;

CREATE TABLE CITY_GEOGRAPHIC (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),
    ID_STATE INTEGER,

    CONSTRAINT PK_CITY_GEOGRAPHIC_ID PRIMARY KEY (ID),
    CONSTRAINT NN_CITY_GEOGRAPHIC_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT FK_CITY_GEO_STATE_GEO_ID FOREIGN KEY (ID_STATE) REFERENCES STATE_GEOGRAPHIC(ID),
    CONSTRAINT NN_CITY_GEOGRAPHIC_ID_STATE CHECK (ID_STATE IS NOT NULL)
);

CREATE GENERATOR SQ_CITY_GEOGRAPHIC_ID;

SET TERM ^ ;
CREATE TRIGGER BI_CITY_GEOGRAPHIC_ID
FOR CITY_GEOGRAPHIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_CITY_GEOGRAPHIC_ID;
END^
SET TERM ; ^

INSERT INTO CITY_GEOGRAPHIC (DESCRIPTION, ID_STATE) VALUES ('ACARATUBA', 24);


INSERT INTO METADATA (NAME, COMMENT) VALUES ('CITY_GEOGRAPHIC', 'TABLE TO STORE CITY GEOGRAPHIC VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_CITY_GEOGRAPHIC_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE CITY GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_CITY_GEOGRAPHIC_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE CITY GEOGRAPHIC COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CITY_GEO_STATE_GEO_ID', 'FOREIGN KEY REFERENCES STATE_GEOGRAPHIC (ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_CITY_GEOGRAPHIC_ID_STATE', 'NOT NULL CONSTRAINT FOR TABLE CITY GEOGRAPHIC COLUMN ID_STATE.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_CITY_GEOGRAPHIC_ID', 'GENERATOR FOR TABLE CITY GEOGRAPHIC COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_CITY_GEOGRAPHIC_ID', 'TRIGGER FOR TABLE CITY GEOGRAPHIC COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('CITY_GEOGRAPHIC.ID', 'UNIQUE IDENTIFIER FOR THE CITY GEOGRAPHIC.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CITY_GEOGRAPHIC.DESCRIPTION', 'DESCRIPTION OF THE CITY GEOGRAPHIC.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CITY_GEOGRAPHIC.ID_STATE', 'FOREIGN KEY STATE_GEOGRAPHIC(ID).');

COMMIT WORK;

CREATE TABLE REGISTRATION_STATUS (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_REGISTRATION_STATUS_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_REGISTRATION_STATUS_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_REGISTRATION_STATUS_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_REGISTRATION_STATUS_ID;

SET TERM ^ ;
CREATE TRIGGER BI_REGISTRATION_STATUS_ID
FOR REGISTRATION_STATUS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_REGISTRATION_STATUS_ID;
END^
SET TERM ; ^

INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('ATIVO');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('INATIVO');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('PENDENCIA FINANCEIRA');
INSERT INTO REGISTRATION_STATUS (DESCRIPTION) VALUES ('PENDENCIA ADMINISTRATIVA');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('REGISTRATION_STATUS', 'TABLE TO STORE REGISTRATION STATUS VALUES.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_REGISTRATION_STATUS_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE REGISTRATION_STATUS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_REGISTRATION_STATUS_DESCRIPTION', 'UNIQUE CONSTRAINT FOR TABLE REGISTRATION_STATUS COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_REGISTRATION_STATUS_DESCRIPTION', 'NOT NULL CONSTRAINT FOR TABLE REGISTRATION_STATUS COLUMN DESCRIPTION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_REGISTRATION_STATUS_ID', 'GENERATOR FOR TABLE REGISTRATION_STATUS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_REGISTRATION_STATUS_ID', 'TRIGGER FOR TABLE REGISTRATION_STATUS COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('REGISTRATION_STATUS.ID', 'UNIQUE IDENTIFIER FOR THE REGISTRATION STATUS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('REGISTRATION_STATUS.DESCRIPTION', 'DESCRIPTION OF THE REGISTRATION STATUS.');

COMMIT WORK;

CREATE TABLE CUSTOMER_REGISTRATION (
    ID INTEGER,

    NAME_BIOLOGICAL VARCHAR(150),
    NAME_SOCIAL VARCHAR(150),

    IDENTITY VARCHAR(25),

    ID_BIOLOGICAL_SEX INTEGER,
    ID_SEXUAL_ORIENTATION INTEGER,
    ID_GENDER_EXPRESSION INTEGER,
    ID_GENDER_IDENTITY INTEGER,

    ID_ETHNIC_GROUP INTEGER,
    ID_JOB_OCCUPATION INTEGER,
    ID_MARITAL_STATUS INTEGER,
    ID_RELIGIOUS_AFFILIATION INTEGER,

    ID_REGISTRATION_STATUS INTEGER,

    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_CUSTOMER_REGISTRATION_ID PRIMARY KEY (ID),
    CONSTRAINT NN_CUSTOMER_REGISTRATION_NAME_BIOLOGICAL CHECK (NAME_BIOLOGICAL IS NOT NULL),
    CONSTRAINT FK_CUSTOMER_REG_BIOLOGICAL_SEX_ID FOREIGN KEY (ID_BIOLOGICAL_SEX) REFERENCES BIOLOGICAL_SEX(ID),
    CONSTRAINT FK_CUSTOMER_REG_SEXUAL_ORI_ID FOREIGN KEY (ID_SEXUAL_ORIENTATION) REFERENCES SEXUAL_ORIENTATION(ID),
    CONSTRAINT FK_CUSTOMER_REG_GENDER_EXP_ID FOREIGN KEY (ID_GENDER_EXPRESSION) REFERENCES GENDER_EXPRESSION(ID),
    CONSTRAINT FK_CUSTOMER_REG_GENDER_IDE_ID FOREIGN KEY (ID_GENDER_IDENTITY) REFERENCES GENDER_IDENTITY(ID),
    CONSTRAINT FK_CUSTOMER_REG_ETHNIC_GRO_ID FOREIGN KEY (ID_ETHNIC_GROUP) REFERENCES ETHNIC_GROUP(ID),
    CONSTRAINT FK_CUSTOMER_REG_JOB_OCC_ID FOREIGN KEY (ID_JOB_OCCUPATION) REFERENCES JOB_OCCUPATION(ID),
    CONSTRAINT FK_CUSTOMER_REG_MARITAL_STA_ID FOREIGN KEY (ID_MARITAL_STATUS) REFERENCES MARITAL_STATUS(ID),
    CONSTRAINT FK_CUSTOMER_REG_RELIGIOUS_AFF_ID FOREIGN KEY (ID_RELIGIOUS_AFFILIATION) REFERENCES RELIGIOUS_AFFILIATION(ID)
);

CREATE GENERATOR SQ_CUSTOMER_REGISTRATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_CUSTOMER_REGISTRATION_ID
FOR CUSTOMER_REGISTRATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_CUSTOMER_REGISTRATION_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION', 'TABLE TO STORE CUSTOMER REGISTRATION DETAILS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_CUSTOMER_REGISTRATION_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE CUSTOMER_REGISTRATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_CUSTOMER_REGISTRATION_NAME_BIOLOGICAL', 'NOT NULL CONSTRAINT FOR TABLE CUSTOMER_REGISTRATION COLUMN NAME_BIOLOGICAL.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_BIOLOGICAL_SEX_ID', 'FOREIGN KEY REFERENCES BIOLOGICAL_SEX(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_SEXUAL_ORI_ID', 'FOREIGN KEY REFERENCES SEXUAL_ORIENTATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_GENDER_EXP_ID', 'FOREIGN KEY REFERENCES GENDER_EXPRESSION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_GENDER_IDE_ID', 'FOREIGN KEY REFERENCES GENDER_IDENTITY(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_ETHNIC_GRO_ID', 'FOREIGN KEY REFERENCES ETHNIC_GROUP(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_JOB_OCC_ID', 'FOREIGN KEY REFERENCES JOB_OCCUPATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_MARITAL_STA_ID', 'FOREIGN KEY REFERENCES MARITAL_STATUS(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_CUSTOMER_REG_RELIGIOUS_AFF_ID', 'FOREIGN KEY REFERENCES RELIGIOUS_AFFILIATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_CUSTOMER_REGISTRATION_ID', 'GENERATOR FOR TABLE CUSTOMER_REGISTRATION COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_CUSTOMER_REGISTRATION_ID', 'TRIGGER FOR TABLE CUSTOMER_REGISTRATION COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID', 'UNIQUE IDENTIFIER FOR THE CUSTOMER REGISTRATION.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.NAME_BIOLOGICAL', 'LEGAL/BIOLOGICAL NAME OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.NAME_SOCIAL', 'SOCIAL NAME OF THE CUSTOMER IF DIFFERENT FROM BIOLOGICAL NAME.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.IDENTITY', 'IDENTITY DOCUMENT NUMBER (RG) OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_BIOLOGICAL_SEX', 'REFERENCE TO THE BIOLOGICAL SEX OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_SEXUAL_ORIENTATION', 'REFERENCE TO THE SEXUAL ORIENTATION OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_GENDER_EXPRESSION', 'REFERENCE TO THE GENDER EXPRESSION OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_GENDER_IDENTITY', 'REFERENCE TO THE GENDER IDENTITY OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_ETHNIC_GROUP', 'REFERENCE TO THE ETHNIC GROUP OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_JOB_OCCUPATION', 'REFERENCE TO THE JOB OR OCCUPATION OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_MARITAL_STATUS', 'REFERENCE TO THE MARITAL STATUS OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_RELIGIOUS_AFFILIATION', 'REFERENCE TO THE RELIGIOUS AFFILIATION OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.ID_REGISTRATION_STATUS', 'REFERENCE TO THE REGISTRATION STATUS OF THE CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CUSTOMER_REGISTRATION.OBSERVATION', 'ADDITIONAL NOTES ABOUT THE CUSTOMER REGISTRATION.');

COMMIT WORK;

CREATE TABLE RESIDENTIAL_ADDRESS (
    ID INTEGER,
    ID_CUSTOMER INTEGER,

    ADDRESS VARCHAR(150),
    NUMBER VARCHAR(8),
    NEIGHBORHOOD VARCHAR(75),
    CEP VARCHAR(15),
    COMPLEMENT VARCHAR(75),

    PHONE_DDD CHAR(2),
    PHONE_NUMBER VARCHAR(10),

    MAIL VARCHAR(75),

    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_RESIDENTIAL_ADDRESS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_RESIDENTIAL_ADD_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT UQ_RESIDENTIAL_ADDRESS_ID_CUSTOMER UNIQUE (ID_CUSTOMER),
    CONSTRAINT NN_RESIDENTIAL_ADDRESS_ID_CUSTOMER CHECK (ID_CUSTOMER IS NOT NULL)
);

CREATE GENERATOR SQ_RESIDENTIAL_ADDRESS_ID;

SET TERM ^ ;
CREATE TRIGGER BI_RESIDENTIAL_ADDRESS_ID
FOR RESIDENTIAL_ADDRESS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_RESIDENTIAL_ADDRESS_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS', 'TABLE TO STORE RESIDENTIAL ADDRESS DETAILS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_RESIDENTIAL_ADDRESS_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE RESIDENTIAL_ADDRESS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_RESIDENTIAL_ADD_CUSTOMER_REG_ID', 'FOREIGN KEY REFERENCES CUSTOMER_REGISTRATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_RESIDENTIAL_ADDRESS_ID_CUSTOMER', 'UNIQUE CONSTRAINT FOR TABLE RESIDENTIAL_ADDRESS COLUMN ID_CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_RESIDENTIAL_ADDRESS_ID_CUSTOMER', 'NOT NULL CONSTRAINT FOR TABLE RESIDENTIAL_ADDRESS COLUMN ID_CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_RESIDENTIAL_ADDRESS_ID', 'GENERATOR FOR TABLE RESIDENTIAL_ADDRESS COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_RESIDENTIAL_ADDRESS_ID', 'TRIGGER FOR TABLE RESIDENTIAL_ADDRESS COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.ID', 'UNIQUE IDENTIFIER FOR THE RESIDENTIAL ADDRESS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.ID_CUSTOMER', 'REFERENCE TO THE CUSTOMER TO WHOM THIS ADDRESS BELONGS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.ADDRESS', 'STREET NAME OR ADDRESS DETAILS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.NUMBER', 'HOUSE OR BUILDING NUMBER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.NEIGHBORHOOD', 'NEIGHBORHOOD OF THE RESIDENCE.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.CEP', 'POSTAL CODE OF THE RESIDENTIAL ADDRESS.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.COMPLEMENT', 'ADDITIONAL DETAILS SUCH AS APARTMENT NUMBER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.PHONE_DDD', 'AREA CODE FOR THE RESIDENTIAL PHONE.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.PHONE_NUMBER', 'PHONE NUMBER ASSOCIATED WITH THIS RESIDENCE.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.MAIL', 'EMAIL ADDRESS ASSOCIATED WITH THIS RESIDENCE.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('RESIDENTIAL_ADDRESS.OBSERVATION', 'ADDITIONAL NOTES ABOUT THE RESIDENTIAL ADDRESS.');

COMMIT WORK;

CREATE TABLE FAMILY_CENTER (
    ID INTEGER,
    ID_CUSTOMER INTEGER,

    FATHER_NAME VARCHAR(150),
    FATHER_AGE SMALLINT,
    ID_FATHER_JOB_OCC INT,

    MOTHER_NAME VARCHAR(150),
    MOTHER_AGE SMALLINT,
    ID_MOTHER_JOB_OCC INT,

    PARTNER_NAME VARCHAR(150),
    PARTNER_AGE SMALLINT,
    ID_PARTNER_JOB_OCC INT,

    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_FAMILY_CENTER_ID PRIMARY KEY (ID),
    CONSTRAINT FK_FAMILY_CEN_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT UQ_FAMILY_CENTER_ID_CUSTOMER UNIQUE (ID_CUSTOMER),
    CONSTRAINT NN_FAMILY_CENTER_ID_CUSTOMER CHECK (ID_CUSTOMER IS NOT NULL),
    CONSTRAINT FK_FAMILY_CEN_JOB_OCC_ID_FATHER_JOB_OCC FOREIGN KEY (ID_FATHER_JOB_OCC) REFERENCES JOB_OCCUPATION(ID),
    CONSTRAINT FK_FAMILY_CEN_JOB_OCC_ID_MOTHER_JOB_OCC FOREIGN KEY (ID_MOTHER_JOB_OCC) REFERENCES JOB_OCCUPATION(ID),
    CONSTRAINT FK_FAMILY_CEN_JOB_OCC_ID_PARTNER_JOB_OCC FOREIGN KEY (ID_PARTNER_JOB_OCC) REFERENCES JOB_OCCUPATION(ID)
);

CREATE GENERATOR SQ_FAMILY_CENTER_ID;

SET TERM ^ ;
CREATE TRIGGER BI_FAMILY_CENTER_ID
FOR FAMILY_CENTER
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_FAMILY_CENTER_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER', 'TABLE TO STORE FAMILY CENTER DETAILS OF A CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_FAMILY_CENTER_ID', 'PRIMARY KEY CONSTRAINT FOR TABLE FAMILY_CENTER COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_CEN_CUSTOMER_REG_ID', 'FOREIGN KEY REFERENCES CUSTOMER_REGISTRATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UQ_FAMILY_CENTER_ID_CUSTOMER', 'UNIQUE CONSTRAINT FOR TABLE FAMILY_CENTER COLUMN ID_CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_FAMILY_CENTER_ID_CUSTOMER', 'NOT NULL CONSTRAINT FOR TABLE FAMILY_CENTER COLUMN ID_CUSTOMER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_CEN_JOB_OCC_ID_FATHER_JOB_OCC', 'FOREIGN KEY REFERENCES JOB_OCCUPATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_CEN_JOB_OCC_ID_MOTHER_JOB_OCC', 'FOREIGN KEY REFERENCES JOB_OCCUPATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_CEN_JOB_OCC_ID_PARTNER_JOB_OCC', 'FOREIGN KEY REFERENCES JOB_OCCUPATION(ID).');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_FAMILY_CENTER_ID', 'GENERATOR FOR TABLE FAMILY_CENTER COLUMN ID.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_FAMILY_CENTER_ID', 'TRIGGER FOR TABLE FAMILY_CENTER COLUMN ID.');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.ID', 'UNIQUE IDENTIFIER FOR THE FAMILY CENTER RECORD.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.ID_CUSTOMER', 'REFERENCE TO THE CUSTOMER ASSOCIATED WITH THIS FAMILY CENTER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.FATHER_NAME', 'NAME OF THE CUSTOMERS FATHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.FATHER_AGE', 'AGE OF THE CUSTOMERS FATHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.ID_FATHER_JOB_OCC', 'REFERENCE TO THE JOB OCCUPATION OF THE CUSTOMERS FATHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.MOTHER_NAME', 'NAME OF THE CUSTOMERS MOTHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.MOTHER_AGE', 'AGE OF THE CUSTOMERS MOTHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.ID_MOTHER_JOB_OCC', 'REFERENCE TO THE JOB OCCUPATION OF THE CUSTOMERS MOTHER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.PARTNER_NAME', 'NAME OF THE CUSTOMERS PARTNER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.PARTNER_AGE', 'AGE OF THE CUSTOMERS PARTNER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.ID_PARTNER_JOB_OCC', 'REFERENCE TO THE JOB OCCUPATION OF THE CUSTOMERS PARTNER.');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_CENTER.OBSERVATION', 'ADDITIONAL NOTES ABOUT THE FAMILY CENTER RECORD.');

COMMIT WORK;

CREATE TABLE CHAPTER_ANAMNESIS (
    ID INTEGER,
    DESCRIPTION VARCHAR(75),

    CONSTRAINT PK_CHAPTER_ANAMNESIS_ID PRIMARY KEY (ID),
    CONSTRAINT UN_CHAPTER_ANAMNESIS_DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT NN_CHAPTER_ANAMNESIS_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL)
);

CREATE GENERATOR SQ_CHAPTER_ANAMNESIS_ID;

SET TERM ^ ;
CREATE TRIGGER BI_CHAPTER_ANAMNESIS_ID
FOR CHAPTER_ANAMNESIS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_CHAPTER_ANAMNESIS_ID;
END^
SET TERM ; ^

INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('IDENTIFICACAO DO PACIENTE');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('QUEIXA PRINCIPAL LATENTE');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HISTORICO FAMILIAR');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HISTORICO DE SAUDE');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HISTORICO PROFISSIONAL');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HISTORICO ACADEMICO');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HISTORICO SOCIAL');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('ASPECTOS EMOCIONAIS');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('HABITO ROTINA E LAZER');
INSERT INTO CHAPTER_ANAMNESIS (DESCRIPTION) VALUES ('EXPECTATIVA DA TERAPIA');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('CHAPTER_ANAMNESIS', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_CHAPTER_ANAMNESIS_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('UN_CHAPTER_ANAMNESIS_DESCRIPTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_CHAPTER_ANAMNESIS_DESCRIPTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_CHAPTER_ANAMNESIS_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_CHAPTER_ANAMNESIS_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('CHAPTER_ANAMNESIS.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('CHAPTER_ANAMNESIS.DESCRIPTION', '');

COMMIT WORK;

CREATE TABLE QUESTION_SCHEDULE (
    ID INTEGER,
    ID_CHAPTER INTEGER,
    QUESTION VARCHAR(255),

    CONSTRAINT PK_QUESTION_SCHEDULE_ID PRIMARY KEY (ID),
    CONSTRAINT FK_QUESTION_SCH_CHAPTER_ANA_ID FOREIGN KEY (ID_CHAPTER) REFERENCES CHAPTER_ANAMNESIS(ID),
    CONSTRAINT NN_QUESTION_SCHEDULE_ID_CHAPTER CHECK (ID_CHAPTER IS NOT NULL),
    CONSTRAINT NN_QUESTION_SCHEDULE_QUESTION CHECK (QUESTION IS NOT NULL)
);

CREATE GENERATOR SQ_QUESTION_SCHEDULE_ID;

SET TERM ^ ;
CREATE TRIGGER BI_QUESTION_SCHEDULE_ID
FOR QUESTION_SCHEDULE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_QUESTION_SCHEDULE_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('QUESTION_SCHEDULE', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_QUESTION_SCHEDULE_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_QUESTION_SCH_CHAPTER_ANA_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_QUESTION_SCHEDULE_ID_CHAPTER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_QUESTION_SCHEDULE_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_QUESTION_SCHEDULE_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_QUESTION_SCHEDULE_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('QUESTION_SCHEDULE.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('QUESTION_SCHEDULE.ID_CHAPTER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('QUESTION_SCHEDULE.QUESTION', '');

COMMIT WORK;

CREATE TABLE PATIENT_IDENTIFICATION (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_PATIENT_IDENTIFICATION_ID PRIMARY KEY (ID),
    CONSTRAINT FK_PATIENT_IDE_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_PATIENT_IDE_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_PATIENT_IDENTIFICATION_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_PATIENT_IDENTIFICATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_PATIENT_IDENTIFICATION_ID
FOR PATIENT_IDENTIFICATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_PATIENT_IDENTIFICATION_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PATIENT_IDENTIFICATION_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PATIENT_IDENTIFICATION_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE MAIN_COMPLAINT (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_MAIN_COMPLAINT_ID PRIMARY KEY (ID),
    CONSTRAINT FK_MAIN_COM_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_MAIN_COM_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_MAIN_COMPLAINT_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_MAIN_COMPLAINT_ID;

SET TERM ^ ;
CREATE TRIGGER BI_MAIN_COMPLAINT_ID
FOR MAIN_COMPLAINT
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_MAIN_COMPLAINT_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_MAIN_COMPLAINT_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_MAIN_COM_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_MAIN_COM_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_MAIN_COMPLAINT_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_MAIN_COMPLAINT_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_MAIN_COMPLAINT_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('MAIN_COMPLAINT.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE FAMILY_HISTORY (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_FAMILY_HISTORY_ID PRIMARY KEY (ID),
    CONSTRAINT FK_FAMILY_HIS_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_FAMILY_HIS_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_FAMILY_HISTORY_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_FAMILY_HISTORY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_FAMILY_HISTORY_ID
FOR FAMILY_HISTORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_FAMILY_HISTORY_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_FAMILY_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_HIS_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_FAMILY_HIS_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_FAMILY_HISTORY_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_FAMILY_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_FAMILY_HISTORY_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FAMILY_HISTORY.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE HEALTH_HISTORY (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_HEALTH_HISTORY_ID PRIMARY KEY (ID),
    CONSTRAINT FK_HEALTH_HIS_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_HEALTH_HIS_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_HEALTH_HISTORY_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_HEALTH_HISTORY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_HEALTH_HISTORY_ID
FOR HEALTH_HISTORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_HEALTH_HISTORY_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_HEALTH_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_HEALTH_HIS_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_HEALTH_HIS_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_HEALTH_HISTORY_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_HEALTH_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_HEALTH_HISTORY_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('HEALTH_HISTORY.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE PROFESSIONAL_HISTORY (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_PROFESSIONAL_HISTORY_ID PRIMARY KEY (ID),
    CONSTRAINT FK_PROFESSIONAL_HIS_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_PROFESSIONAL_HIS_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_PROFESSIONAL_HISTORY_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_PROFESSIONAL_HISTORY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_PROFESSIONAL_HISTORY_ID
FOR PROFESSIONAL_HISTORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_PROFESSIONAL_HISTORY_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PROFESSIONAL_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PROFESSIONAL_HIS_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PROFESSIONAL_HIS_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PROFESSIONAL_HISTORY_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PROFESSIONAL_HISTORY_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PROFESSIONAL_HISTORY_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PROFESSIONAL_HISTORY.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE ACADEMIC_HISTORY (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_ACADEMIC_HISTORY_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ACADEMIC_HIS_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_ACADEMIC_HIS_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_ACADEMIC_HISTORY_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_ACADEMIC_HISTORY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_ACADEMIC_HISTORY_ID
FOR ACADEMIC_HISTORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_ACADEMIC_HISTORY_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PATIENT_IDENTIFICATION_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PATIENT_IDENTIFICATION_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE SOCIAL_HISTORY (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_SOCIAL_HISTORY_ID PRIMARY KEY (ID),
    CONSTRAINT FK_SOCIAL_HIS_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_SOCIAL_HIS_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_SOCIAL_HISTORY_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_SOCIAL_HISTORY_ID;

SET TERM ^ ;
CREATE TRIGGER BI_SOCIAL_HISTORY_ID
FOR SOCIAL_HISTORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_SOCIAL_HISTORY_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PATIENT_IDENTIFICATION_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PATIENT_IDENTIFICATION_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE EMOTIONAL_ASPECT (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_EMOTIONAL_ASPECT_ID PRIMARY KEY (ID),
    CONSTRAINT FK_EMOTIONAL_ASP_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_EMOTIONAL_ASP_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_EMOTIONAL_ASPECT_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_EMOTIONAL_ASPECT_ID;

SET TERM ^ ;
CREATE TRIGGER BI_EMOTIONAL_ASPECT_ID
FOR EMOTIONAL_ASPECT
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_EMOTIONAL_ASPECT_ID;
END^
SET TERM ; ^

CREATE TABLE ROUTINE_HABIT (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_ROUTINE_HABIT_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ROUTINE_HAB_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_ROUTINE_HAB_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_ROUTINE_HABIT_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_ROUTINE_HABIT_ID;

SET TERM ^ ;
CREATE TRIGGER BI_ROUTINE_HABIT_ID
FOR ROUTINE_HABIT
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_ROUTINE_HABIT_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PATIENT_IDENTIFICATION_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PATIENT_IDENTIFICATION_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.OBSERVATION', '');

COMMIT WORK;

CREATE TABLE THERAPY_EXPECTATION (
    ID INTEGER, 
    ID_CUSTOMER INTEGER,
    ID_QUESTION INTEGER,
    ANSWER VARCHAR(255),
    OBSERVATION VARCHAR(255),

    CONSTRAINT PK_THERAPY_EXPECTATION_ID PRIMARY KEY (ID),
    CONSTRAINT FK_THERAPY_EXP_CUSTOMER_REG_ID FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER_REGISTRATION(ID),
    CONSTRAINT FK_THERAPY_EXP_QUESTION_SCH_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION_SCHEDULE(ID),
    CONSTRAINT NN_THERAPY_EXPECTATION_ANSWER CHECK (ANSWER IS NOT NULL)
);

CREATE GENERATOR SQ_THERAPY_EXPECTATION_ID;

SET TERM ^ ;
CREATE TRIGGER BI_THERAPY_EXPECTATION_ID
FOR THERAPY_EXPECTATION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SQ_THERAPY_EXPECTATION_ID;
END^
SET TERM ; ^

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PK_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_CUSTOMER_REG_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('FK_PATIENT_IDE_QUESTION_SCH_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('NN_PATIENT_IDENTIFICATION_ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('SQ_PATIENT_IDENTIFICATION_ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('BI_PATIENT_IDENTIFICATION_ID', '');

INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_CUSTOMER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ID_QUESTION', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.ANSWER', '');
INSERT INTO METADATA (NAME, COMMENT) VALUES ('PATIENT_IDENTIFICATION.OBSERVATION', '');

COMMIT WORK;
