/*
TABLE TBCOUNTRY: TABLE CONTAINING INFORMATION ABOUT COUNTRIES
*/

CREATE TABLE TBCOUNTRY(
    	ID_ SERIAL NOT NULL PRIMARY KEY,
    	NAME VARCHAR(45) NOT NULL UNIQUE
);

COMMIT WORK;

COMMENT ON TABLE TBCOUNTRY IS 'TABLE CONTAINING INFORMATION ABOUT COUNTRIES';
COMMENT ON COLUMN TBCOUNTRY.ID_ IS 'UNIQUE IDENTIFIER FOR EACH COUNTRY';
COMMENT ON COLUMN TBCOUNTRY.NAME IS 'NAME OF THE COUNTRY';

COMMIT WORK;

INSERT INTO TBCOUNTRY (NAME) VALUES ('BRASIL');

COMMIT WORK;
