/*
TABLE TBGENDEREXPRESSION: TABLE TO STORE GENDER EXPRESSION CATEGORIES
*/

CREATE TABLE TBGENDEREXPRESSION (
    	ID_ SERIAL NOT NULL PRIMARY KEY,
    	NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBGENDEREXPRESSION IS 'TABLE TO STORE GENDER EXPRESSION CATEGORIES.';
COMMENT ON COLUMN TBGENDEREXPRESSION.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.NAME IS 'NAME OF THE GENDER EXPRESSION CATEGORY.';
COMMENT ON COLUMN TBGENDEREXPRESSION.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER EXPRESSION CATEGORY.';

COMMIT WORK;

INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('MASCULINA', 'A EXPRESSAO DE GENERO QUE POSSUI TRACOS TIPICOS DOS HOMENS E MENINOS E CLASSIFICADA COMO EXPRESSAO DE GENERO MASCULINA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FEMININA', 'A EXPRESSAO DE GENERO QUE CONTEM CARACTERISTICAS TIPICAS DAS MULHERES E MENINAS E CLASSIFICADA COMO EXPRESSAO DE GENERO FEMININA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('ANDROGINA', 'UMA EXPRESSAO DE GENERO QUE INCLUA TRACOS TIPICOS DOS HOMENS E MENINOS, E TRACOS TIPICOS DAS MULHERES E MENINAS, E CLASSIFICADA COMO ANDROGINA.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('FLUIDA', 'E A NAO IDENTIFICACAO COM UM UNICO PAPEL DE GENERO OU IDENTIDADE DE GENERO, FLUINDO ENTRE VARIOS. SAO TAMBEM AQUELAS CUJO GENERO E INSOLITO OU MUDA DE TEMPOS EM TEMPOS.');
INSERT INTO TBGENDEREXPRESSION (NAME, OBSERVATION) VALUES ('NAO BINARIA', 'E UM TERMO GUARDA-CHUVA PARA IDENTIDADES DE GENERO QUE NAO SAO ESTRITAMENTE MASCULINAS OU FEMININAS, ESTANDO PORTANTO FORA DO BINARIO DE GENERO E DA CISNORMATIVIDADE.');

COMMIT WORK;
