/*
TABLE TBGENDERIDENTITY: TABLE TO STORE GENDER IDENTITY CATEGORIES
*/

CREATE TABLE TBGENDERIDENTITY (
    	ID_ SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(45) NOT NULL UNIQUE,
	OBSERVATION VARCHAR(255)
);

COMMIT WORK;

COMMENT ON TABLE TBGENDERIDENTITY IS 'TABLE TO STORE GENDER IDENTITY CATEGORIES.';
COMMENT ON COLUMN TBGENDERIDENTITY.ID_ IS 'UNIQUE IDENTIFIER FOR THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.NAME IS 'NAME OF THE GENDER IDENTITY CATEGORY.';
COMMENT ON COLUMN TBGENDERIDENTITY.OBSERVATION IS 'ADDITIONAL OBSERVATIONS OR COMMENTS REGARDING THE GENDER IDENTITY CATEGORY.';

COMMIT WORK;

INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('CISGENERO', 'E A CONDICAO DA PESSOA CUJA IDENTIDADE DE GENERO CORRESPONDE AO SEXO QUE LHE FOI ATRIBUIDO NO NASCIMENTO.');
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('TRANSGENERO', 'SAO PESSOAS CUJA IDENTIDADE DE GENERO DIFERE DO TIPICO DO SEU SEXO, ATRIBUIDO AO NASCER.');
INSERT INTO TBGENDERIDENTITY (NAME, OBSERVATION) VALUES ('INTERSEXUAL', 'E A PESSOA QUE NATURALMENTE DESENVOLVE CARACTERISTICAS SEXUAIS QUE NAO SE ENCAIXAM NAS NOCOES TIPICAS DE SEXO FEMININO OU SEXO MASCULINO.');

COMMIT WORK;
