/*
TABLE TBSTATE: TABLE CONTAINING INFORMATION ABOUT STATES
*/

CREATE TABLE TBSTATE(
    ID_ SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    IDCOUNTRY_ INTEGER NOT NULL,

    FOREIGN KEY (IDCOUNTRY_) REFERENCES TBCOUNTRY(ID_)
);

COMMIT WORK;

COMMENT ON TABLE TBSTATE IS 'TABLE CONTAINING INFORMATION ABOUT STATES';
COMMENT ON COLUMN TBSTATE.ID_ IS 'UNIQUE IDENTIFIER FOR EACH STATE';
COMMENT ON COLUMN TBSTATE.NAME IS 'NAME OF THE STATE';
COMMENT ON COLUMN TBSTATE.IDCOUNTRY_ IS 'FOREIGN KEY REFERENCING THE UNIQUE IDENTIFIER OF THE COUNTRY IN THE TBCOUNTRY TABLE';

COMMIT WORK;

INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ACRE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ALAGOAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('AMAPA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('AMAZONAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('BAHIA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('CEARA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('ESPIRITO SANTO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('GOIAS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MARANHAO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MATO GROSSO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MATO GROSSO DO SUL', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('MINAS GERAIS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARAIBA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PARANA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PERNAMBUCO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('PIAUI', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO DE JANEIRO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO GRANDE DO NORTE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RIO GRANDE DO SUL', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RONDONIA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('RORAIMA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SANTA CATARINA', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SAO PAULO', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('SERGIPE', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('TOCANTINS', 1);
INSERT INTO TBSTATE (NAME, IDCOUNTRY_) VALUES ('DISTRITO FEDERAL', 1);

COMMIT WORK;
