TABLE METADATA {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  SCHEMA VARCHAR [UNIQUE, NOT NULL]
  COMMENT VARCHAR
}

TABLE BIOLOGICALSEX {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE GENDEREXPRESSION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE SEXUALORIENTATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE GENDERIDENTITY {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}

TABLE COUNTRYGEOGRAPHIC {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE STATEGEOGRAPHIC {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_COUNTRY INTEGER [NOT NULL, REF: > COUNTRYGEOGRAPHIC.ID]
  DESCRIPTION VARCHAR [NOT NULL]
}
TABLE CITYGEOGRAPHIC {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_STATE INTEGER [NOT NULL, REF: > STATEGEOGRAPHIC.ID]
  DESCRIPTION VARCHAR [NOT NULL]
}

TABLE MARITALSTATUS {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE JOBOCCUPATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE RELIGIOUSAFFILIATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE ETHNICGROUP {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
} 
TABLE ACADEMICDEGREE {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE MONTHLYINCOME {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE MEDICALINSURANCE {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE REGISTRATIONSTATUS {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE BLOODTYPE {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}
TABLE DISABILITYPERSON {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  DESCRIPTION VARCHAR [UNIQUE, NOT NULL]
}

TABLE CUSTOMER {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  NAMESOCIAL VARCHAR
  NAMEBIOLOGICAL VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  ID_SEXUALORIENTATION INTEGER [REF: < SEXUALORIENTATION.ID]
  ID_GENDERIDENTITY INTEGER [REF: < GENDERIDENTITY.ID]
  ID_GENDEREXPRESSION INTEGER [REF: < GENDEREXPRESSION.ID]
  BIRTHDATE DATE
  RG VARCHAR
  CPF VARCHAR
  ID_ETHNICGROUP INTEGER [REF: < ETHNICGROUP.ID]
  ID_MARITALSTATUS INTEGER [REF: < MARITALSTATUS.ID]
  ID_RELIGIOUSAFFILIATION INTEGER [REF: < RELIGIOUSAFFILIATION.ID]
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  ID_MONTHLYINCOME INTEGER [REF: < MONTHLYINCOME.ID]
  ID_MEDICALINSURANCE INTEGER [REF: < MEDICALINSURANCE.ID]
  ID_BLOODTYPE INTEGER [REF: < BLOODTYPE.ID]
  ID_DISABILITYPERSON INTEGER [REF: < DISABILITYPERSON.ID]
  ID_REGISTRATIONSTATUS INTEGER [REF: < REGISTRATIONSTATUS.ID]
  OBSERVATION VARCHAR
}

TABLE RESIDENTIALADDRESS {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [UNIQUE, NOT NULL, REF: - CUSTOMER.ID]
  ADDRESS VARCHAR
  NUMBER VARCHAR
  NEIGHBORHOOD VARCHAR 
  COMPLEMENT VARCHAR
  CEP VARCHAR
  ID_CITY INTEGER [REF: < CITYGEOGRAPHIC.ID]
  DDD VARCHAR
  PHONE VARCHAR
  MAIL VARCHAR
  OBSERVATION VARCHAR
}

TABLE MOTHERINFORMATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [NOT NULL, REF: > CUSTOMER.ID]
  NAME VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  AGE TINYINT 
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  OBSERVATION VARCHAR
}
TABLE FATHERINFORMATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [NOT NULL, REF: > CUSTOMER.ID]
  NAME VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  AGE TINYINT 
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  OBSERVATION VARCHAR
}
TABLE BROTHERINFORMATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [NOT NULL, REF: > CUSTOMER.ID]
  NAME VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  AGE TINYINT 
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  OBSERVATION VARCHAR
}
TABLE PARTNERINFORMATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [NOT NULL, REF: > CUSTOMER.ID]
  NAME VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  AGE TINYINT 
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  OBSERVATION VARCHAR
}
TABLE CHILDINFORMATION {
  ID INTEGER [PRIMARY KEY, UNIQUE, NOT NULL]
  ID_CUSTOMER INTEGER [NOT NULL, REF: > CUSTOMER.ID]
  NAME VARCHAR [NOT NULL]
  ID_BIOLOGICALSEX INTEGER [REF: < BIOLOGICALSEX.ID]
  AGE TINYINT 
  ID_JOBOCCUPATION INTEGER [REF: < JOBOCCUPATION.ID]
  ID_ACADEMICDEGREE INTEGER [REF: < ACADEMICDEGREE.ID]
  OBSERVATION VARCHAR
}
